-- SQL script to insert employees into the 'employee' table
-- Generated on 2025-01-08 16:30:02

INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (1, 'Sanne', 'Van den Berg', 'sannevan den berg@protonmail.com', '+31 406-118-549', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (2, 'Grzegorz', 'Kowalczyk', 'kowalczykg@gmail.com', '+48 666-180-787', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (3, 'Alain', 'Lemoine', 'alain.lemoine@zoho.com', '+33 840-191-566', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (4, 'Philipp', 'Schulze', 'pschulze@protonmail.com', '+49 788-426-790', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (5, 'Moritz', 'Schmidt', 'schmidtm@mail.com', '+49 305-258-407', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (6, 'Moritz', 'Zimmer', 'moritzzimmer@yandex.com', '+49 575-505-254', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (7, 'Jane', 'Smith', 'smithj@protonmail.com', '+48 951-693-461', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (8, 'Marcin', 'Kruk', 'marcinkruk@outlook.com', '+48 138-993-498', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (9, 'Jakub', 'Woźniak', 'jakub.woźniak@protonmail.com', '+48 191-815-174', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (10, 'Jakub', 'Sikora', 'jakub.sikora@yahoo.com', '+48 549-038-914', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (11, 'Michel', 'Joly', 'michel291@outlook.com', '+33 834-982-078', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (12, 'Jane', 'Smith', 'janesmith93@hotmail.com', '+48 971-779-983', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (13, 'Petra', 'Bartošová', 'pbartošová@hotmail.com', '+420 446-241-458', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (14, 'Rik', 'Visser', 'visserr@yahoo.com', '+31 601-044-314', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (15, 'Wojciech', 'Adamczak', 'adamczakw@mail.com', '+48 043-977-803', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (16, 'Lucia', 'Švecová', 'lšvecová@aol.com', '+421 248-732-554', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (17, 'Zsófia', 'Horváth', 'zsófia824@yahoo.com', '+36 457-658-681', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (18, 'Anna', 'Horváthová', 'horváthováa@protonmail.com', '+421 648-166-799', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (19, 'Réka', 'Tóth', 'rtóth@hotmail.com', '+36 203-898-192', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (20, 'Sophie', 'Vermeulen', 'svermeulen@mail.com', '+32 281-827-685', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (21, 'Laura', 'Gerard', 'laura.gerard@outlook.com', '+32 323-038-198', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (22, 'John', 'Doe', 'johndoe96@gmail.com', '+48 457-057-495', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (23, 'Sophie', 'Jansen', 'sophie.jansen@yahoo.com', '+31 566-738-753', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (24, 'Krisztina', 'Szabó', 'krisztina766@gmail.com', '+36 402-209-731', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (25, 'Krzysztof', 'Kamiński', 'kkamiński@outlook.com', '+48 604-805-482', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (26, 'Elise', 'Huisman', 'huismane@hotmail.com', '+31 708-732-456', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (27, 'Béla', 'Horváth', 'bélahorváth@protonmail.com', '+36 116-711-650', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (28, 'Jean', 'Lefevre', 'lefevrej@protonmail.com', '+33 091-123-413', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (29, 'Laura', 'Szabó', 'szaból@aol.com', '+36 943-098-492', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (30, 'Sebastian', 'Jäger', 'sebastianjäger30@yandex.com', '+49 696-454-259', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (31, 'Sanne', 'Huisman', 'sannehuisman@icloud.com', '+31 111-201-734', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (32, 'Karolina', 'Nováková', 'karolinanováková75@hotmail.com', '+420 116-269-971', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (33, 'Sarah', 'De Smet', 'sarah.de smet@mail.com', '+32 400-602-300', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (34, 'Helena', 'Rózová', 'helenarózová69@aol.com', '+421 927-551-925', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (35, 'Pierre', 'Leclerc', 'pierreleclerc@mail.com', '+33 439-683-252', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (36, 'Roman', 'Dvořák', 'romandvořák1@protonmail.com', '+420 797-925-493', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (37, 'Dominik', 'Petrík', 'dominikpetrík@zoho.com', '+421 117-187-590', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (38, 'John', 'Doe', 'doej@hotmail.com', '+48 839-311-013', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (39, 'Barbora', 'Kučerová', 'barborakučerová@aol.com', '+420 682-703-294', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (40, 'Peter', 'Tóth', 'tóthp@outlook.com', '+421 363-133-146', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (41, 'Lukáš', 'Švec', 'lukáš.švec@zoho.com', '+421 652-500-641', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (42, 'Jane', 'Smith', 'janesmith@aol.com', '+48 068-639-728', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (43, 'Tomáš', 'Kašpar', 'tomáškašpar@protonmail.com', '+421 181-158-134', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (44, 'David', 'Vondráček', 'davidvondráček@mail.com', '+420 012-736-165', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (45, 'Júlia', 'Kovács', 'júlia563@mail.com', '+36 883-818-888', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (46, 'Szymon', 'Chmiel', 'szymonchmiel63@yandex.com', '+48 210-465-647', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (47, 'Johan', 'Hendrickx', 'johan893@outlook.com', '+32 491-933-341', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (48, 'Luc', 'Lenaerts', 'llenaerts@zoho.com', '+32 062-369-957', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (49, 'Jane', 'Smith', 'jane394@yandex.com', '+48 897-755-474', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (50, 'Jane', 'Smith', 'jsmith@zoho.com', '+48 073-331-919', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (51, 'John', 'Doe', 'john321@yandex.com', '+48 135-931-067', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (52, 'Florian', 'Schulz', 'florianschulz@zoho.com', '+49 743-048-384', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (53, 'Klara', 'Seidel', 'seidelk@protonmail.com', '+49 419-763-632', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (54, 'Mieke', 'Visser', 'mieke.visser@hotmail.com', '+31 612-903-029', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (55, 'Gábor', 'Lukács', 'gáborlukács95@protonmail.com', '+36 784-775-196', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (56, 'Julia', 'De Vries', 'jde vries@hotmail.com', '+31 246-115-627', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (57, 'Sarah', 'Smit', 'sarah.smit@yahoo.com', '+31 126-861-389', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (58, 'Johan', 'Verbeek', 'johanverbeek@icloud.com', '+31 207-619-798', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (59, 'Blanka', 'Németh', 'blankanémeth81@protonmail.com', '+36 634-917-442', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (60, 'Tom', 'De Smet', 'de smett@protonmail.com', '+32 597-107-863', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (61, 'Claire', 'David', 'cdavid@protonmail.com', '+33 867-455-731', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (62, 'David', 'Vondráček', 'david146@yahoo.com', '+420 807-531-559', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (63, 'Miroslav', 'Pavol', 'miroslavpavol10@gmail.com', '+421 033-650-997', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (64, 'John', 'Doe', 'johndoe@zoho.com', '+48 706-078-584', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (65, 'Petra', 'Nováková', 'novákováp@yahoo.com', '+420 976-455-014', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (66, 'Piotr', 'Kowalczyk', 'kowalczykp@yahoo.com', '+48 829-053-119', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (67, 'Mia', 'Van den Berg', 'miavan den berg14@aol.com', '+31 571-132-928', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (68, 'Vincent', 'Peeters', 'vincent757@icloud.com', '+32 002-886-341', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (69, 'Camille', 'Serruys', 'camilleserruys@gmail.com', '+32 888-784-235', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (70, 'Eszter', 'Németh', 'eszter592@yandex.com', '+36 664-959-402', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (71, 'Zoë', 'Van der Linden', 'van der lindenz@yahoo.com', '+31 327-322-356', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (72, 'Sebastian', 'Schmidt', 'sebastian.schmidt@outlook.com', '+49 404-177-341', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (73, 'Veronika', 'Černá', 'veronikačerná@aol.com', '+420 153-684-118', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (74, 'Attila', 'Kiss', 'kissa@icloud.com', '+36 736-409-650', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (75, 'Miklós', 'Tóth', 'miklóstóth6@protonmail.com', '+36 332-281-048', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (76, 'Lucia', 'Horváthová', 'horváthovál@zoho.com', '+421 323-877-456', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (77, 'John', 'Doe', 'jdoe@gmail.com', '+48 615-984-371', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (78, 'Julie', 'Jacques', 'jjacques@mail.com', '+32 079-339-639', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (79, 'Michel', 'Leclerc', 'mleclerc@zoho.com', '+33 395-994-366', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (80, 'Miroslav', 'Varga', 'vargam@zoho.com', '+421 902-018-335', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (81, 'Petra', 'Kováčová', 'petrakováčová14@gmail.com', '+421 376-814-981', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (82, 'Krisztina', 'Németh', 'krisztinanémeth@hotmail.com', '+36 583-112-638', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (83, 'Laura', 'Serruys', 'lauraserruys67@hotmail.com', '+32 292-442-596', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (84, 'Jane', 'Smith', 'janesmith@outlook.com', '+48 892-827-856', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (85, 'Lena', 'Hartmann', 'lenahartmann@icloud.com', '+49 220-208-026', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (86, 'István', 'Molnár', 'istván.molnár@aol.com', '+36 692-436-900', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (87, 'Julia', 'Van den Berg', 'juliavan den berg@aol.com', '+31 245-515-734', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (88, 'John', 'Doe', 'john.doe@yahoo.com', '+48 602-926-225', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (89, 'Rik', 'Bakker', 'rikbakker@gmail.com', '+31 356-663-280', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (90, 'Sophie', 'Jansen', 'sophie.jansen@aol.com', '+31 231-005-332', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (91, 'Jan', 'Wróblewski', 'jan.wróblewski@aol.com', '+48 088-221-642', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (92, 'Eva', 'Kováčová', 'eva.kováčová@yandex.com', '+421 808-963-397', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (93, 'Claire', 'Tanguy', 'ctanguy@mail.com', '+33 002-746-202', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (94, 'Joanna', 'Dąbrowska', 'dąbrowskaj@hotmail.com', '+48 594-823-051', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (95, 'Petr', 'Heřman', 'petrheřman@aol.com', '+420 635-603-389', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (96, 'Réka', 'Tóth', 'tóthr@icloud.com', '+36 561-144-049', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (97, 'Jozef', 'Varga', 'jozef.varga@outlook.com', '+421 808-116-389', 0);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (98, 'Andrej', 'Novák', 'andrej912@yandex.com', '+421 456-535-453', 1);
INSERT INTO employee (employee_id, first_name, last_name, email, phone, is_active) VALUES (99, 'Chloé', 'Lemoine', 'clemoine@outlook.com', '+33 796-471-114', 1);
