INSERT INTO cities (city_id, country_id, name) VALUES (1, 'PL', 'Warsaw (Marszałkowska)');
INSERT INTO cities (city_id, country_id, name) VALUES (2, 'PL', 'Warsaw (Pięciomorgowa)');
INSERT INTO cities (city_id, country_id, name) VALUES (3, 'PL', 'Warsaw (Wrzesińska)');
INSERT INTO cities (city_id, country_id, name) VALUES (4, 'PL', 'Warsaw (Królewska (Royal))');
INSERT INTO cities (city_id, country_id, name) VALUES (5, 'PL', 'Warsaw (Królewska Ziemia)');
INSERT INTO cities (city_id, country_id, name) VALUES (6, 'PL', 'Warsaw (Jana Pawła II (John Paul II))');
INSERT INTO cities (city_id, country_id, name) VALUES (7, 'PL', 'Warsaw (Księcia Janusza (Prince Janusz))');
INSERT INTO cities (city_id, country_id, name) VALUES (8, 'PL', 'Warsaw (Rynkowska)');
INSERT INTO cities (city_id, country_id, name) VALUES (9, 'PL', 'Warsaw (Włodkowica)');
INSERT INTO cities (city_id, country_id, name) VALUES (10, 'PL', 'Warsaw (Nowogrodzka)');
INSERT INTO cities (city_id, country_id, name) VALUES (11, 'PL', 'Kraków (Floriańska)');
INSERT INTO cities (city_id, country_id, name) VALUES (12, 'PL', 'Kraków (Grodzka)');
INSERT INTO cities (city_id, country_id, name) VALUES (13, 'PL', 'Kraków (Nowa (New))');
INSERT INTO cities (city_id, country_id, name) VALUES (14, 'PL', 'Kraków (Długa (Long))');
INSERT INTO cities (city_id, country_id, name) VALUES (15, 'PL', 'Kraków (Pawia)');
INSERT INTO cities (city_id, country_id, name) VALUES (16, 'PL', 'Kraków (Ratuszowa)');
INSERT INTO cities (city_id, country_id, name) VALUES (17, 'PL', 'Kraków (Mazowiecka)');
INSERT INTO cities (city_id, country_id, name) VALUES (18, 'PL', 'Kraków (Starowiślna)');
INSERT INTO cities (city_id, country_id, name) VALUES (19, 'PL', 'Kraków (Cystersów (Cistercians))');
INSERT INTO cities (city_id, country_id, name) VALUES (20, 'PL', 'Łódź (Piotrkowska)');
INSERT INTO cities (city_id, country_id, name) VALUES (21, 'PL', 'Łódź (Narutowicza)');
INSERT INTO cities (city_id, country_id, name) VALUES (22, 'PL', 'Łódź (Tuwima)');
INSERT INTO cities (city_id, country_id, name) VALUES (23, 'PL', 'Łódź (Wólczańska)');
INSERT INTO cities (city_id, country_id, name) VALUES (24, 'PL', 'Łódź (Żeromskiego)');
INSERT INTO cities (city_id, country_id, name) VALUES (25, 'PL', 'Łódź (Struga)');
INSERT INTO cities (city_id, country_id, name) VALUES (26, 'PL', 'Łódź (Sienkiewicza)');
INSERT INTO cities (city_id, country_id, name) VALUES (27, 'PL', 'Łódź (Pilsudskiego)');
INSERT INTO cities (city_id, country_id, name) VALUES (28, 'PL', 'Łódź (Pięciomorgowa)');
INSERT INTO cities (city_id, country_id, name) VALUES (29, 'PL', 'Łódź (Zgierska)');
INSERT INTO cities (city_id, country_id, name) VALUES (30, 'DE', 'Berlin (Unter den Linden (Under the Linden Trees))');
INSERT INTO cities (city_id, country_id, name) VALUES (31, 'DE', 'Berlin (Friedrichstraße)');
INSERT INTO cities (city_id, country_id, name) VALUES (32, 'DE', 'Berlin (Alexanderplatz)');
INSERT INTO cities (city_id, country_id, name) VALUES (33, 'DE', 'Berlin (Karl-Marx-Allee)');
INSERT INTO cities (city_id, country_id, name) VALUES (34, 'DE', 'Berlin (Sonnenallee (Sun Avenue))');
INSERT INTO cities (city_id, country_id, name) VALUES (35, 'DE', 'Berlin (Kottbusser Damm)');
INSERT INTO cities (city_id, country_id, name) VALUES (36, 'DE', 'Berlin (Potsdamer Straße)');
INSERT INTO cities (city_id, country_id, name) VALUES (37, 'DE', 'Berlin (Schlesische Straße)');
INSERT INTO cities (city_id, country_id, name) VALUES (38, 'DE', 'Berlin (Leipziger Straße)');
INSERT INTO cities (city_id, country_id, name) VALUES (39, 'DE', 'Berlin (Am Köllnischen Park)');
INSERT INTO cities (city_id, country_id, name) VALUES (40, 'DE', 'Munich (Maximilianstraße)');
INSERT INTO cities (city_id, country_id, name) VALUES (41, 'DE', 'Munich (Sendlinger Straße)');
INSERT INTO cities (city_id, country_id, name) VALUES (42, 'DE', 'Munich (Leopoldstraße)');
INSERT INTO cities (city_id, country_id, name) VALUES (43, 'DE', 'Munich (Rosenheimer Straße)');
INSERT INTO cities (city_id, country_id, name) VALUES (44, 'DE', 'Munich (Theresienstraße)');
INSERT INTO cities (city_id, country_id, name) VALUES (45, 'DE', 'Munich (Gabelsbergerstraße)');
INSERT INTO cities (city_id, country_id, name) VALUES (46, 'DE', 'Munich (Haidhausen)');
INSERT INTO cities (city_id, country_id, name) VALUES (47, 'DE', 'Munich (Augustinerstraße)');
INSERT INTO cities (city_id, country_id, name) VALUES (48, 'DE', 'Munich (Goetheplatz)');
INSERT INTO cities (city_id, country_id, name) VALUES (49, 'DE', 'Hamburg (Jungfernstieg)');
INSERT INTO cities (city_id, country_id, name) VALUES (50, 'DE', 'Hamburg (Mönckebergstraße)');
INSERT INTO cities (city_id, country_id, name) VALUES (51, 'DE', 'Hamburg (Reeperbahn)');
INSERT INTO cities (city_id, country_id, name) VALUES (52, 'DE', 'Hamburg (Grosse Freiheit)');
INSERT INTO cities (city_id, country_id, name) VALUES (53, 'DE', 'Hamburg (Spitalerstraße)');
INSERT INTO cities (city_id, country_id, name) VALUES (54, 'DE', 'Hamburg (Neuer Wall)');
INSERT INTO cities (city_id, country_id, name) VALUES (55, 'DE', 'Hamburg (Lange Reihe)');
INSERT INTO cities (city_id, country_id, name) VALUES (56, 'DE', 'Hamburg (Schanzenstraße)');
INSERT INTO cities (city_id, country_id, name) VALUES (57, 'DE', 'Hamburg (Alsterufer)');
INSERT INTO cities (city_id, country_id, name) VALUES (58, 'FR', 'Paris (Champs-Élysées)');
INSERT INTO cities (city_id, country_id, name) VALUES (59, 'FR', 'Paris (Rue de Rivoli)');
INSERT INTO cities (city_id, country_id, name) VALUES (60, 'FR', 'Paris (Rue de la Paix)');
INSERT INTO cities (city_id, country_id, name) VALUES (61, 'FR', 'Paris (Boulevard Saint-Germain)');
INSERT INTO cities (city_id, country_id, name) VALUES (62, 'FR', 'Paris (Avenue des Champs-Élysées)');
INSERT INTO cities (city_id, country_id, name) VALUES (63, 'FR', 'Paris (Rue Saint-Honoré)');
INSERT INTO cities (city_id, country_id, name) VALUES (64, 'FR', 'Paris (Rue Montmartre)');
INSERT INTO cities (city_id, country_id, name) VALUES (65, 'FR', 'Paris (Boulevard Haussmann)');
INSERT INTO cities (city_id, country_id, name) VALUES (66, 'FR', 'Paris (Rue du Faubourg Saint-Antoine)');
INSERT INTO cities (city_id, country_id, name) VALUES (67, 'FR', 'Marseille (Rue de la République)');
INSERT INTO cities (city_id, country_id, name) VALUES (68, 'FR', 'Marseille (Avenue de la Canebière)');
INSERT INTO cities (city_id, country_id, name) VALUES (69, 'FR', 'Marseille (Rue Saint-Ferréol)');
INSERT INTO cities (city_id, country_id, name) VALUES (70, 'FR', 'Marseille (Rue Paradis)');
INSERT INTO cities (city_id, country_id, name) VALUES (71, 'FR', 'Marseille (Boulevard Longchamp)');
INSERT INTO cities (city_id, country_id, name) VALUES (72, 'FR', 'Marseille (Quai des Belges)');
INSERT INTO cities (city_id, country_id, name) VALUES (73, 'FR', 'Marseille (Avenue des Chartreux)');
INSERT INTO cities (city_id, country_id, name) VALUES (74, 'FR', 'Marseille (Rue de Lodi)');
INSERT INTO cities (city_id, country_id, name) VALUES (75, 'FR', 'Marseille (Rue du Théâtre)');
INSERT INTO cities (city_id, country_id, name) VALUES (76, 'FR', 'Lyon (Rue de la République)');
INSERT INTO cities (city_id, country_id, name) VALUES (77, 'FR', 'Lyon (Rue Mercière)');
INSERT INTO cities (city_id, country_id, name) VALUES (78, 'FR', 'Lyon (Boulevard de la Croix-Rousse)');
INSERT INTO cities (city_id, country_id, name) VALUES (79, 'FR', 'Lyon (Place Bellecour)');
INSERT INTO cities (city_id, country_id, name) VALUES (80, 'FR', 'Lyon (Rue des Marronniers)');
INSERT INTO cities (city_id, country_id, name) VALUES (81, 'FR', 'Lyon (Rue Victor Hugo)');
INSERT INTO cities (city_id, country_id, name) VALUES (82, 'FR', 'Lyon (Rue de l'Université)');
INSERT INTO cities (city_id, country_id, name) VALUES (83, 'FR', 'Lyon (Rue Jean Jaurès)');
INSERT INTO cities (city_id, country_id, name) VALUES (84, 'FR', 'Lyon (Avenue Jean Jaurès)');
INSERT INTO cities (city_id, country_id, name) VALUES (85, 'FR', 'Lyon (Place des Terreaux)');
INSERT INTO cities (city_id, country_id, name) VALUES (86, 'BE', 'Brussels (Rue de la Loi (Law Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (87, 'BE', 'Brussels (Boulevard Anspach)');
INSERT INTO cities (city_id, country_id, name) VALUES (88, 'BE', 'Brussels (Rue de la Montagne (Mountain Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (89, 'BE', 'Brussels (Rue Neuve (New Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (90, 'BE', 'Brussels (Avenue Louise)');
INSERT INTO cities (city_id, country_id, name) VALUES (91, 'BE', 'Brussels (Rue Royale)');
INSERT INTO cities (city_id, country_id, name) VALUES (92, 'BE', 'Brussels (Rue de Flandre)');
INSERT INTO cities (city_id, country_id, name) VALUES (93, 'BE', 'Brussels (Chaussée de Louvain)');
INSERT INTO cities (city_id, country_id, name) VALUES (94, 'BE', 'Brussels (Rue du Midi (South Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (95, 'BE', 'Brussels (Boulevard de Waterloo)');
INSERT INTO cities (city_id, country_id, name) VALUES (96, 'BE', 'Antwerp (Meir)');
INSERT INTO cities (city_id, country_id, name) VALUES (97, 'BE', 'Antwerp (Grote Markt (Big Market))');
INSERT INTO cities (city_id, country_id, name) VALUES (98, 'BE', 'Antwerp (Kloosterstraat (Monastery Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (99, 'BE', 'Antwerp (Rue de la Cathédrale (Cathedral Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (100, 'BE', 'Antwerp (Groenplaats (Green Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (101, 'BE', 'Antwerp (Keyserlei)');
INSERT INTO cities (city_id, country_id, name) VALUES (102, 'BE', 'Antwerp (De Keyserlei)');
INSERT INTO cities (city_id, country_id, name) VALUES (103, 'BE', 'Antwerp (Verversrui)');
INSERT INTO cities (city_id, country_id, name) VALUES (104, 'BE', 'Antwerp (Schipperskwartier (Ship's Quarter))');
INSERT INTO cities (city_id, country_id, name) VALUES (105, 'BE', 'Ghent (Korenmarkt (Grain Market))');
INSERT INTO cities (city_id, country_id, name) VALUES (106, 'BE', 'Ghent (Veldstraat)');
INSERT INTO cities (city_id, country_id, name) VALUES (107, 'BE', 'Ghent (Hoogstraat (High Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (108, 'BE', 'Ghent (Vrijdagmarkt (Friday Market))');
INSERT INTO cities (city_id, country_id, name) VALUES (109, 'BE', 'Ghent (Belfortstraat (Belfry Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (110, 'NL', 'Amsterdam (Damstraat (Dam Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (111, 'NL', 'Amsterdam (Leidseplein (Leiden Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (112, 'NL', 'Amsterdam (Kalverstraat (Calf Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (113, 'NL', 'Amsterdam (Prinsengracht (Prince's Canal))');
INSERT INTO cities (city_id, country_id, name) VALUES (114, 'NL', 'Amsterdam (Vondelpark)');
INSERT INTO cities (city_id, country_id, name) VALUES (115, 'NL', 'Amsterdam (Spuistraat (Spui Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (116, 'NL', 'Amsterdam (Rembrandtplein (Rembrandt Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (117, 'NL', 'Amsterdam (Utrechtsestraat (Utrecht Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (118, 'NL', 'Amsterdam (Haarlemmerdijk (Haarlem Dyke))');
INSERT INTO cities (city_id, country_id, name) VALUES (119, 'NL', 'Amsterdam (Nieuwendijk (New Dike))');
INSERT INTO cities (city_id, country_id, name) VALUES (120, 'NL', 'Rotterdam (Lijnbaan)');
INSERT INTO cities (city_id, country_id, name) VALUES (121, 'NL', 'Rotterdam (Coolsingel)');
INSERT INTO cities (city_id, country_id, name) VALUES (122, 'NL', 'Rotterdam (Witte de Withstraat)');
INSERT INTO cities (city_id, country_id, name) VALUES (123, 'NL', 'Rotterdam (West-Kruiskade)');
INSERT INTO cities (city_id, country_id, name) VALUES (124, 'NL', 'Rotterdam (Boompjes)');
INSERT INTO cities (city_id, country_id, name) VALUES (125, 'NL', 'Rotterdam (Sint-Jobshaven (St. Job's Harbor))');
INSERT INTO cities (city_id, country_id, name) VALUES (126, 'NL', 'Rotterdam (Schiedamseweg)');
INSERT INTO cities (city_id, country_id, name) VALUES (127, 'NL', 'Rotterdam (Weena)');
INSERT INTO cities (city_id, country_id, name) VALUES (128, 'NL', 'Rotterdam (Beursplein (Exchange Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (129, 'NL', 'The Hague (Lange Voorhout (Long Forecourt))');
INSERT INTO cities (city_id, country_id, name) VALUES (130, 'NL', 'The Hague (Frederik Hendriklaan)');
INSERT INTO cities (city_id, country_id, name) VALUES (131, 'NL', 'The Hague (Noordeinde (North End))');
INSERT INTO cities (city_id, country_id, name) VALUES (132, 'NL', 'The Hague (Wagenstraat (Wagon Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (133, 'NL', 'The Hague (Spui)');
INSERT INTO cities (city_id, country_id, name) VALUES (134, 'NL', 'The Hague (Grote Marktstraat (Big Market Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (135, 'NL', 'The Hague (Anna Paulownastraat)');
INSERT INTO cities (city_id, country_id, name) VALUES (136, 'NL', 'The Hague (Oude Molstraat (Old Mill Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (137, 'NL', 'The Hague (Prinsessegracht (Princess Canal))');
INSERT INTO cities (city_id, country_id, name) VALUES (138, 'CZ', 'Prague (Václavské náměstí (Wenceslas Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (139, 'CZ', 'Prague (Na Příkopě)');
INSERT INTO cities (city_id, country_id, name) VALUES (140, 'CZ', 'Prague (Wenceslas Square)');
INSERT INTO cities (city_id, country_id, name) VALUES (141, 'CZ', 'Prague (Národní)');
INSERT INTO cities (city_id, country_id, name) VALUES (142, 'CZ', 'Prague (Karoliny Světlé)');
INSERT INTO cities (city_id, country_id, name) VALUES (143, 'CZ', 'Prague (Karlovo náměstí (Charles Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (144, 'CZ', 'Prague (Revoluční (Revolutionary))');
INSERT INTO cities (city_id, country_id, name) VALUES (145, 'CZ', 'Prague (Jindřišská)');
INSERT INTO cities (city_id, country_id, name) VALUES (146, 'CZ', 'Prague (Týnská)');
INSERT INTO cities (city_id, country_id, name) VALUES (147, 'CZ', 'Prague (Malá Strana (Lesser Town))');
INSERT INTO cities (city_id, country_id, name) VALUES (148, 'CZ', 'Brno (Masarykova)');
INSERT INTO cities (city_id, country_id, name) VALUES (149, 'CZ', 'Brno (Cejl)');
INSERT INTO cities (city_id, country_id, name) VALUES (150, 'CZ', 'Brno (Česká)');
INSERT INTO cities (city_id, country_id, name) VALUES (151, 'CZ', 'Brno (Náměstí Svobody (Freedom Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (152, 'CZ', 'Brno (Veveří)');
INSERT INTO cities (city_id, country_id, name) VALUES (153, 'CZ', 'Brno (Tkalcovská)');
INSERT INTO cities (city_id, country_id, name) VALUES (154, 'CZ', 'Brno (Dornych)');
INSERT INTO cities (city_id, country_id, name) VALUES (155, 'CZ', 'Brno (Špitálka)');
INSERT INTO cities (city_id, country_id, name) VALUES (156, 'CZ', 'Brno (Koliště)');
INSERT INTO cities (city_id, country_id, name) VALUES (157, 'CZ', 'Brno (Pekařská)');
INSERT INTO cities (city_id, country_id, name) VALUES (158, 'CZ', 'Ostrava (Stodolní)');
INSERT INTO cities (city_id, country_id, name) VALUES (159, 'CZ', 'Ostrava (Masarykova)');
INSERT INTO cities (city_id, country_id, name) VALUES (160, 'CZ', 'Ostrava (Karolina)');
INSERT INTO cities (city_id, country_id, name) VALUES (161, 'CZ', 'Ostrava (Opavská)');
INSERT INTO cities (city_id, country_id, name) VALUES (162, 'CZ', 'Ostrava (Nádražní)');
INSERT INTO cities (city_id, country_id, name) VALUES (163, 'CZ', 'Ostrava (Mírové náměstí (Peace Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (164, 'CZ', 'Ostrava (Hranická)');
INSERT INTO cities (city_id, country_id, name) VALUES (165, 'CZ', 'Ostrava (Klimkovická)');
INSERT INTO cities (city_id, country_id, name) VALUES (166, 'CZ', 'Ostrava (Ruská)');
INSERT INTO cities (city_id, country_id, name) VALUES (167, 'CZ', 'Ostrava (Českobratrská)');
INSERT INTO cities (city_id, country_id, name) VALUES (168, 'SK', 'Bratislava (Hviezdoslavovo námestie (Hviezdoslav Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (169, 'SK', 'Bratislava (Karadžičova)');
INSERT INTO cities (city_id, country_id, name) VALUES (170, 'SK', 'Bratislava (Obchodná)');
INSERT INTO cities (city_id, country_id, name) VALUES (171, 'SK', 'Bratislava (Špitálska)');
INSERT INTO cities (city_id, country_id, name) VALUES (172, 'SK', 'Bratislava (Námestie SNP (SNP Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (173, 'SK', 'Bratislava (Dostojevského rad)');
INSERT INTO cities (city_id, country_id, name) VALUES (174, 'SK', 'Bratislava (Panská)');
INSERT INTO cities (city_id, country_id, name) VALUES (175, 'SK', 'Bratislava (Mlynské nivy)');
INSERT INTO cities (city_id, country_id, name) VALUES (176, 'SK', 'Bratislava (Ružinovská)');
INSERT INTO cities (city_id, country_id, name) VALUES (177, 'SK', 'Bratislava (Petržalka)');
INSERT INTO cities (city_id, country_id, name) VALUES (178, 'SK', 'Košice (Hlavná (Main))');
INSERT INTO cities (city_id, country_id, name) VALUES (179, 'SK', 'Košice (Masarykova)');
INSERT INTO cities (city_id, country_id, name) VALUES (180, 'SK', 'Košice (Kuzmányho)');
INSERT INTO cities (city_id, country_id, name) VALUES (181, 'SK', 'Košice (Mlynská)');
INSERT INTO cities (city_id, country_id, name) VALUES (182, 'SK', 'Košice (Námestie Maratónu Mieru (Peace Marathon Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (183, 'SK', 'Košice (Lichnerova)');
INSERT INTO cities (city_id, country_id, name) VALUES (184, 'SK', 'Košice (Strojárenská)');
INSERT INTO cities (city_id, country_id, name) VALUES (185, 'SK', 'Košice (Kováčska)');
INSERT INTO cities (city_id, country_id, name) VALUES (186, 'SK', 'Košice (Alejová)');
INSERT INTO cities (city_id, country_id, name) VALUES (187, 'SK', 'Nitra (Špitálska)');
INSERT INTO cities (city_id, country_id, name) VALUES (188, 'SK', 'Nitra (Bratislavská)');
INSERT INTO cities (city_id, country_id, name) VALUES (189, 'SK', 'Nitra (Chrenovská)');
INSERT INTO cities (city_id, country_id, name) VALUES (190, 'SK', 'Nitra (Svätoplukova)');
INSERT INTO cities (city_id, country_id, name) VALUES (191, 'SK', 'Nitra (Fatranská)');
INSERT INTO cities (city_id, country_id, name) VALUES (192, 'SK', 'Nitra (Biskupická)');
INSERT INTO cities (city_id, country_id, name) VALUES (193, 'SK', 'Nitra (Na Drahách)');
INSERT INTO cities (city_id, country_id, name) VALUES (194, 'SK', 'Nitra (Tríbečská)');
INSERT INTO cities (city_id, country_id, name) VALUES (195, 'SK', 'Nitra (Kmeťova)');
INSERT INTO cities (city_id, country_id, name) VALUES (196, 'SK', 'Nitra (Kováčska)');
INSERT INTO cities (city_id, country_id, name) VALUES (197, 'HU', 'Budapest (Andrássy út)');
INSERT INTO cities (city_id, country_id, name) VALUES (198, 'HU', 'Budapest (Váci utca)');
INSERT INTO cities (city_id, country_id, name) VALUES (199, 'HU', 'Budapest (Rákóczi út)');
INSERT INTO cities (city_id, country_id, name) VALUES (200, 'HU', 'Budapest (Kossuth Lajos utca)');
INSERT INTO cities (city_id, country_id, name) VALUES (201, 'HU', 'Budapest (József körút)');
INSERT INTO cities (city_id, country_id, name) VALUES (202, 'HU', 'Budapest (Nagykörút (Grand Boulevard))');
INSERT INTO cities (city_id, country_id, name) VALUES (203, 'HU', 'Budapest (Rakpart)');
INSERT INTO cities (city_id, country_id, name) VALUES (204, 'HU', 'Budapest (Hősök tere (Heroes' Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (205, 'HU', 'Budapest (Deák Ferenc tér (Deák Ferenc Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (206, 'HU', 'Budapest (Bajcsy-Zsilinszky út)');
INSERT INTO cities (city_id, country_id, name) VALUES (207, 'HU', 'Debrecen (Kossuth Lajos utca)');
INSERT INTO cities (city_id, country_id, name) VALUES (208, 'HU', 'Debrecen (Piac utca (Market Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (209, 'HU', 'Debrecen (Batthyány utca)');
INSERT INTO cities (city_id, country_id, name) VALUES (210, 'HU', 'Debrecen (Ady Endre utca)');
INSERT INTO cities (city_id, country_id, name) VALUES (211, 'HU', 'Debrecen (Szoboszlói út)');
INSERT INTO cities (city_id, country_id, name) VALUES (212, 'HU', 'Debrecen (Derék utca)');
INSERT INTO cities (city_id, country_id, name) VALUES (213, 'HU', 'Debrecen (Csemete utca)');
INSERT INTO cities (city_id, country_id, name) VALUES (214, 'HU', 'Debrecen (Böszörményi út)');
INSERT INTO cities (city_id, country_id, name) VALUES (215, 'HU', 'Debrecen (Kossuth tér (Kossuth Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (216, 'HU', 'Szeged (Kossuth Lajos sugárút)');
INSERT INTO cities (city_id, country_id, name) VALUES (217, 'HU', 'Szeged (Deák Ferenc utca)');
INSERT INTO cities (city_id, country_id, name) VALUES (218, 'HU', 'Szeged (Széchenyi tér (Széchenyi Square))');
INSERT INTO cities (city_id, country_id, name) VALUES (219, 'HU', 'Szeged (Vasút utca (Railroad Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (220, 'HU', 'Szeged (Tisza Lajos körút)');
INSERT INTO cities (city_id, country_id, name) VALUES (221, 'HU', 'Szeged (Béke utca (Peace Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (222, 'HU', 'Szeged (Rózsa utca (Rose Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (223, 'HU', 'Szeged (Lázár utca (Lazarus Street))');
INSERT INTO cities (city_id, country_id, name) VALUES (224, 'HU', 'Szeged (Kálvária sugárút)');
