-- Generated on 2025-01-15 22:37
-- COMMIT EVERY 1000 ROWS

SET FOREIGN_KEY_CHECKS=0;

INSERT INTO college_class (class_id, name, college_id, semester) VALUES (1, 'Parallel Computing', 1, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (2, 'Database Systems', 1, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (3, 'Data Structures', 1, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (4, 'Cybersecurity Fundamentals', 1, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (5, 'Software Engineering', 1, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (6, 'Algorithms', 1, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (7, 'Introduction to Programming', 1, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (8, 'Parallel Computing', 1, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (9, 'Mobile Development', 1, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (10, 'Web Development', 1, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (21, 'Introduction to Programming', 2, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (22, 'Introduction to Programming', 2, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (23, 'Cloud Computing', 2, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (24, 'Cybersecurity Fundamentals', 2, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (25, 'Data Structures', 2, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (26, 'Software Engineering', 2, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (27, 'Introduction to Programming', 2, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (28, 'Project Management', 2, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (41, 'Data Structures', 3, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (42, 'Project Management', 3, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (43, 'Statistical Analysis', 3, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (44, 'Algorithms', 3, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (45, 'Computer Architecture', 3, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (46, 'Cybersecurity Fundamentals', 3, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (47, 'Robotics', 3, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (48, 'System Design', 3, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (49, 'Game Development', 3, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (50, 'Algorithms', 3, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (51, 'Robotics', 3, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (52, 'Mobile Development', 3, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (53, 'Parallel Computing', 3, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (61, 'Computer Graphics', 4, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (62, 'Computer Architecture', 4, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (63, 'Game Development', 4, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (64, 'Data Mining', 4, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (65, 'Cybersecurity Fundamentals', 4, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (66, 'Introduction to Programming', 4, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (67, 'Advanced Mathematics', 4, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (68, 'Operating Systems', 4, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (81, 'Database Systems', 5, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (82, 'Data Mining', 5, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (83, 'Digital Marketing', 5, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (84, 'Cloud Computing', 5, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (85, 'Blockchain Technology', 5, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (86, 'Data Structures', 5, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (87, 'Data Structures', 5, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (88, 'Advanced Mathematics', 5, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (89, 'Mobile Development', 5, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (90, 'Internet of Things', 5, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (91, 'Robotics', 5, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (92, 'Algorithms', 5, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (93, 'Machine Learning', 5, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (101, 'Embedded Systems', 6, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (102, 'Data Mining', 6, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (103, 'Business Analytics', 6, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (104, 'Parallel Computing', 6, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (105, 'Computer Networks', 6, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (106, 'Computer Architecture', 6, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (107, 'Algorithms', 6, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (108, 'Natural Language Processing', 6, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (109, 'Introduction to Programming', 6, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (110, 'Machine Learning', 6, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (111, 'Cloud Computing', 6, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (121, 'Web Development', 7, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (122, 'Data Mining', 7, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (123, 'Game Development', 7, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (124, 'Machine Learning', 7, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (125, 'Business Analytics', 7, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (126, 'System Design', 7, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (127, 'Cybersecurity Fundamentals', 7, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (128, 'Operating Systems', 7, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (141, 'Cloud Computing', 8, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (142, 'Internet of Things', 8, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (143, 'Software Engineering', 8, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (144, 'Software Engineering', 8, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (145, 'Machine Learning', 8, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (146, 'Database Systems', 8, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (147, 'Mobile Development', 8, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (148, 'Computer Networks', 8, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (149, 'Database Systems', 8, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (150, 'Quantum Computing', 8, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (151, 'Statistical Analysis', 8, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (152, 'Data Structures', 8, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (153, 'Software Engineering', 8, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (154, 'Artificial Intelligence', 8, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (155, 'Computer Architecture', 8, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (161, 'Advanced Mathematics', 9, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (162, 'Internet of Things', 9, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (163, 'Quantum Computing', 9, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (164, 'Project Management', 9, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (165, 'Embedded Systems', 9, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (166, 'Advanced Mathematics', 9, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (167, 'Algorithms', 9, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (168, 'Web Development', 9, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (169, 'Introduction to Programming', 9, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (170, 'Natural Language Processing', 9, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (171, 'Robotics', 9, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (172, 'Digital Marketing', 9, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (173, 'Parallel Computing', 9, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (181, 'Machine Learning', 10, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (182, 'Software Engineering', 10, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (183, 'Artificial Intelligence', 10, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (184, 'Cloud Computing', 10, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (185, 'Computer Graphics', 10, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (186, 'Blockchain Technology', 10, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (187, 'Business Analytics', 10, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (188, 'Project Management', 10, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (189, 'Cloud Computing', 10, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (190, 'Machine Learning', 10, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (191, 'Embedded Systems', 10, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (192, 'Embedded Systems', 10, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (193, 'Computer Graphics', 10, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (201, 'System Design', 11, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (202, 'Data Mining', 11, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (203, 'System Design', 11, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (204, 'Introduction to Programming', 11, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (205, 'Algorithms', 11, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (206, 'Cloud Computing', 11, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (207, 'Parallel Computing', 11, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (208, 'Embedded Systems', 11, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (209, 'Statistical Analysis', 11, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (210, 'Business Analytics', 11, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (211, 'Cloud Computing', 11, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (212, 'Blockchain Technology', 11, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (221, 'Project Management', 12, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (222, 'Web Development', 12, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (223, 'Data Structures', 12, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (224, 'Blockchain Technology', 12, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (225, 'Statistical Analysis', 12, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (226, 'Robotics', 12, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (227, 'Statistical Analysis', 12, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (228, 'Mobile Development', 12, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (229, 'Cybersecurity Fundamentals', 12, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (230, 'Embedded Systems', 12, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (231, 'Database Systems', 12, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (232, 'Advanced Mathematics', 12, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (233, 'Software Engineering', 12, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (234, 'Data Mining', 12, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (241, 'Software Engineering', 13, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (242, 'Project Management', 13, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (243, 'Computer Networks', 13, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (244, 'Artificial Intelligence', 13, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (245, 'Introduction to Programming', 13, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (246, 'Cloud Computing', 13, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (247, 'Computer Networks', 13, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (248, 'Project Management', 13, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (249, 'Project Management', 13, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (250, 'Robotics', 13, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (251, 'Data Structures', 13, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (261, 'Artificial Intelligence', 14, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (262, 'Introduction to Programming', 14, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (263, 'Business Analytics', 14, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (264, 'Data Mining', 14, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (265, 'Computer Graphics', 14, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (266, 'Statistical Analysis', 14, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (267, 'Project Management', 14, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (268, 'Data Mining', 14, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (269, 'Project Management', 14, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (270, 'Internet of Things', 14, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (271, 'Game Development', 14, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (272, 'Computer Graphics', 14, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (273, 'Machine Learning', 14, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (281, 'Embedded Systems', 15, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (282, 'Machine Learning', 15, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (283, 'Digital Marketing', 15, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (284, 'Software Engineering', 15, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (285, 'Computer Graphics', 15, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (286, 'Operating Systems', 15, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (287, 'Quantum Computing', 15, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (288, 'Cloud Computing', 15, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (289, 'Data Mining', 15, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (290, 'Internet of Things', 15, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (291, 'Cloud Computing', 15, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (292, 'System Design', 15, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (293, 'Mobile Development', 15, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (294, 'Embedded Systems', 15, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (295, 'Machine Learning', 15, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (301, 'Statistical Analysis', 16, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (302, 'Cybersecurity Fundamentals', 16, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (303, 'Database Systems', 16, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (304, 'Database Systems', 16, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (305, 'Database Systems', 16, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (306, 'Embedded Systems', 16, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (307, 'Cloud Computing', 16, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (308, 'Data Structures', 16, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (321, 'Cloud Computing', 17, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (322, 'Computer Networks', 17, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (323, 'Machine Learning', 17, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (324, 'Internet of Things', 17, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (325, 'Data Structures', 17, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (326, 'Project Management', 17, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (327, 'Parallel Computing', 17, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (328, 'Advanced Mathematics', 17, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (329, 'Embedded Systems', 17, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (330, 'Project Management', 17, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (331, 'Blockchain Technology', 17, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (332, 'Game Development', 17, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (333, 'Blockchain Technology', 17, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (334, 'Computer Graphics', 17, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (341, 'Computer Graphics', 18, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (342, 'Embedded Systems', 18, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (343, 'Computer Graphics', 18, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (344, 'Algorithms', 18, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (345, 'Internet of Things', 18, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (346, 'Data Structures', 18, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (347, 'Game Development', 18, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (348, 'Quantum Computing', 18, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (349, 'Game Development', 18, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (350, 'Parallel Computing', 18, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (351, 'Operating Systems', 18, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (352, 'Embedded Systems', 18, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (361, 'Operating Systems', 19, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (362, 'Game Development', 19, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (363, 'Parallel Computing', 19, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (364, 'Robotics', 19, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (365, 'Blockchain Technology', 19, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (366, 'System Design', 19, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (367, 'Cloud Computing', 19, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (368, 'Computer Graphics', 19, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (369, 'Natural Language Processing', 19, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (370, 'Project Management', 19, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (381, 'System Design', 20, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (382, 'Web Development', 20, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (383, 'Parallel Computing', 20, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (384, 'Computer Graphics', 20, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (385, 'Computer Architecture', 20, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (386, 'Computer Graphics', 20, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (387, 'Cybersecurity Fundamentals', 20, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (388, 'Data Mining', 20, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (389, 'Data Structures', 20, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (401, 'Operating Systems', 21, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (402, 'Data Mining', 21, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (403, 'Operating Systems', 21, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (404, 'Machine Learning', 21, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (405, 'Blockchain Technology', 21, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (406, 'System Design', 21, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (407, 'Data Structures', 21, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (408, 'Web Development', 21, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (409, 'Statistical Analysis', 21, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (410, 'Statistical Analysis', 21, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (411, 'Data Structures', 21, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (412, 'Computer Networks', 21, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (413, 'Advanced Mathematics', 21, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (414, 'Introduction to Programming', 21, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (421, 'Operating Systems', 22, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (422, 'Blockchain Technology', 22, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (423, 'Blockchain Technology', 22, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (424, 'Blockchain Technology', 22, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (425, 'Computer Networks', 22, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (426, 'Artificial Intelligence', 22, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (427, 'Natural Language Processing', 22, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (428, 'Introduction to Programming', 22, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (429, 'Web Development', 22, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (441, 'System Design', 23, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (442, 'Natural Language Processing', 23, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (443, 'Computer Graphics', 23, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (444, 'Machine Learning', 23, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (445, 'Robotics', 23, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (446, 'Internet of Things', 23, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (447, 'Project Management', 23, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (448, 'Business Analytics', 23, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (449, 'Business Analytics', 23, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (450, 'Database Systems', 23, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (461, 'Computer Architecture', 24, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (462, 'Web Development', 24, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (463, 'Parallel Computing', 24, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (464, 'Project Management', 24, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (465, 'Artificial Intelligence', 24, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (466, 'Machine Learning', 24, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (467, 'Computer Networks', 24, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (468, 'Computer Architecture', 24, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (469, 'Computer Graphics', 24, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (470, 'Quantum Computing', 24, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (471, 'Robotics', 24, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (472, 'Quantum Computing', 24, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (473, 'Introduction to Programming', 24, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (474, 'Statistical Analysis', 24, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (481, 'Algorithms', 25, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (482, 'Machine Learning', 25, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (483, 'Statistical Analysis', 25, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (484, 'Computer Networks', 25, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (485, 'Algorithms', 25, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (486, 'Parallel Computing', 25, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (487, 'Project Management', 25, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (488, 'Parallel Computing', 25, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (501, 'Data Structures', 26, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (502, 'Computer Architecture', 26, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (503, 'Algorithms', 26, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (504, 'Game Development', 26, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (505, 'Web Development', 26, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (506, 'Data Mining', 26, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (507, 'Digital Marketing', 26, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (508, 'Digital Marketing', 26, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (509, 'System Design', 26, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (510, 'Digital Marketing', 26, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (511, 'Computer Architecture', 26, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (512, 'Embedded Systems', 26, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (513, 'System Design', 26, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (514, 'Introduction to Programming', 26, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (521, 'Data Structures', 27, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (522, 'Database Systems', 27, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (523, 'Web Development', 27, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (524, 'Introduction to Programming', 27, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (525, 'Embedded Systems', 27, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (526, 'Embedded Systems', 27, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (527, 'Introduction to Programming', 27, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (528, 'Cybersecurity Fundamentals', 27, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (529, 'Robotics', 27, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (530, 'Quantum Computing', 27, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (531, 'Algorithms', 27, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (532, 'Data Structures', 27, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (533, 'Database Systems', 27, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (534, 'Game Development', 27, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (535, 'Internet of Things', 27, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (541, 'Robotics', 28, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (542, 'Business Analytics', 28, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (543, 'Cybersecurity Fundamentals', 28, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (544, 'Cybersecurity Fundamentals', 28, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (545, 'Operating Systems', 28, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (546, 'Embedded Systems', 28, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (547, 'Operating Systems', 28, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (548, 'Operating Systems', 28, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (549, 'Embedded Systems', 28, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (550, 'Computer Graphics', 28, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (551, 'Game Development', 28, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (552, 'Internet of Things', 28, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (553, 'Database Systems', 28, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (561, 'Algorithms', 29, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (562, 'Computer Networks', 29, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (563, 'Robotics', 29, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (564, 'Software Engineering', 29, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (565, 'Mobile Development', 29, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (566, 'Operating Systems', 29, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (567, 'Parallel Computing', 29, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (568, 'Parallel Computing', 29, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (569, 'Computer Graphics', 29, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (581, 'Artificial Intelligence', 30, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (582, 'Operating Systems', 30, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (583, 'Internet of Things', 30, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (584, 'Quantum Computing', 30, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (585, 'Project Management', 30, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (586, 'Project Management', 30, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (587, 'Computer Architecture', 30, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (588, 'Artificial Intelligence', 30, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (589, 'Internet of Things', 30, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (590, 'Software Engineering', 30, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (591, 'Cybersecurity Fundamentals', 30, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (592, 'Statistical Analysis', 30, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (593, 'Business Analytics', 30, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (601, 'Business Analytics', 31, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (602, 'Internet of Things', 31, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (603, 'Machine Learning', 31, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (604, 'Advanced Mathematics', 31, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (605, 'Project Management', 31, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (606, 'Advanced Mathematics', 31, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (607, 'Software Engineering', 31, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (608, 'Cloud Computing', 31, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (609, 'Web Development', 31, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (610, 'Data Structures', 31, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (611, 'Cloud Computing', 31, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (621, 'Robotics', 32, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (622, 'Data Mining', 32, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (623, 'Software Engineering', 32, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (624, 'Database Systems', 32, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (625, 'Quantum Computing', 32, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (626, 'Advanced Mathematics', 32, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (627, 'Database Systems', 32, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (628, 'Mobile Development', 32, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (629, 'System Design', 32, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (630, 'Embedded Systems', 32, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (631, 'Artificial Intelligence', 32, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (632, 'Machine Learning', 32, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (641, 'Parallel Computing', 33, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (642, 'Advanced Mathematics', 33, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (643, 'Parallel Computing', 33, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (644, 'Game Development', 33, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (645, 'Mobile Development', 33, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (646, 'Operating Systems', 33, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (647, 'System Design', 33, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (648, 'Advanced Mathematics', 33, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (649, 'Cloud Computing', 33, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (650, 'Data Mining', 33, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (651, 'System Design', 33, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (652, 'Blockchain Technology', 33, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (653, 'Operating Systems', 33, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (654, 'Web Development', 33, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (661, 'Statistical Analysis', 34, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (662, 'Machine Learning', 34, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (663, 'Cloud Computing', 34, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (664, 'Blockchain Technology', 34, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (665, 'Advanced Mathematics', 34, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (666, 'Computer Networks', 34, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (667, 'Cybersecurity Fundamentals', 34, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (668, 'Parallel Computing', 34, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (669, 'Operating Systems', 34, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (670, 'Software Engineering', 34, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (671, 'Business Analytics', 34, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (681, 'System Design', 35, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (682, 'Operating Systems', 35, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (683, 'Computer Graphics', 35, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (684, 'Computer Architecture', 35, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (685, 'Statistical Analysis', 35, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (686, 'Introduction to Programming', 35, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (687, 'Advanced Mathematics', 35, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (688, 'Artificial Intelligence', 35, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (689, 'Web Development', 35, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (690, 'Algorithms', 35, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (691, 'System Design', 35, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (692, 'Statistical Analysis', 35, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (693, 'Introduction to Programming', 35, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (701, 'Operating Systems', 36, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (702, 'System Design', 36, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (703, 'Computer Graphics', 36, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (704, 'Statistical Analysis', 36, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (705, 'Advanced Mathematics', 36, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (706, 'System Design', 36, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (707, 'Operating Systems', 36, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (708, 'Statistical Analysis', 36, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (709, 'Database Systems', 36, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (710, 'Algorithms', 36, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (711, 'Web Development', 36, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (712, 'Computer Architecture', 36, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (721, 'Advanced Mathematics', 37, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (722, 'Internet of Things', 37, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (723, 'Blockchain Technology', 37, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (724, 'Business Analytics', 37, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (725, 'Robotics', 37, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (726, 'Natural Language Processing', 37, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (727, 'Mobile Development', 37, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (728, 'Computer Graphics', 37, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (729, 'Game Development', 37, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (730, 'Business Analytics', 37, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (731, 'Project Management', 37, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (732, 'Computer Networks', 37, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (741, 'Data Mining', 38, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (742, 'Internet of Things', 38, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (743, 'Quantum Computing', 38, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (744, 'Algorithms', 38, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (745, 'Database Systems', 38, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (746, 'Computer Graphics', 38, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (747, 'Natural Language Processing', 38, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (748, 'Statistical Analysis', 38, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (749, 'Game Development', 38, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (750, 'Project Management', 38, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (751, 'Algorithms', 38, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (752, 'Mobile Development', 38, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (753, 'Data Mining', 38, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (761, 'Robotics', 39, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (762, 'Game Development', 39, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (763, 'Parallel Computing', 39, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (764, 'Project Management', 39, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (765, 'Cybersecurity Fundamentals', 39, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (766, 'Cloud Computing', 39, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (767, 'Web Development', 39, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (768, 'Project Management', 39, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (769, 'Data Structures', 39, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (781, 'Parallel Computing', 40, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (782, 'Statistical Analysis', 40, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (783, 'Advanced Mathematics', 40, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (784, 'Introduction to Programming', 40, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (785, 'Digital Marketing', 40, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (786, 'Computer Graphics', 40, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (787, 'Robotics', 40, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (788, 'Quantum Computing', 40, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (789, 'Natural Language Processing', 40, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (790, 'Computer Networks', 40, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (791, 'Parallel Computing', 40, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (792, 'Blockchain Technology', 40, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (793, 'Internet of Things', 40, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (794, 'Software Engineering', 40, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (801, 'Internet of Things', 41, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (802, 'Computer Networks', 41, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (803, 'Data Structures', 41, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (804, 'Machine Learning', 41, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (805, 'Machine Learning', 41, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (806, 'Cybersecurity Fundamentals', 41, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (807, 'Artificial Intelligence', 41, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (808, 'Operating Systems', 41, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (809, 'Internet of Things', 41, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (821, 'Robotics', 42, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (822, 'Business Analytics', 42, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (823, 'Computer Networks', 42, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (824, 'Computer Networks', 42, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (825, 'Data Mining', 42, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (826, 'Internet of Things', 42, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (827, 'Blockchain Technology', 42, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (828, 'Business Analytics', 42, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (829, 'Internet of Things', 42, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (830, 'Introduction to Programming', 42, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (831, 'Advanced Mathematics', 42, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (832, 'Project Management', 42, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (841, 'Machine Learning', 43, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (842, 'Computer Graphics', 43, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (843, 'Cybersecurity Fundamentals', 43, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (844, 'Data Structures', 43, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (845, 'Computer Networks', 43, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (846, 'Digital Marketing', 43, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (847, 'Web Development', 43, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (848, 'Mobile Development', 43, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (861, 'Database Systems', 44, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (862, 'Digital Marketing', 44, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (863, 'Internet of Things', 44, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (864, 'Operating Systems', 44, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (865, 'Digital Marketing', 44, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (866, 'Advanced Mathematics', 44, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (867, 'Game Development', 44, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (868, 'Machine Learning', 44, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (869, 'Embedded Systems', 44, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (881, 'Web Development', 45, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (882, 'System Design', 45, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (883, 'Project Management', 45, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (884, 'Quantum Computing', 45, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (885, 'Game Development', 45, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (886, 'Data Mining', 45, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (887, 'Parallel Computing', 45, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (888, 'Computer Architecture', 45, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (889, 'Web Development', 45, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (901, 'Operating Systems', 46, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (902, 'Robotics', 46, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (903, 'Natural Language Processing', 46, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (904, 'Digital Marketing', 46, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (905, 'Computer Architecture', 46, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (906, 'Blockchain Technology', 46, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (907, 'Project Management', 46, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (908, 'Embedded Systems', 46, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (909, 'Database Systems', 46, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (910, 'Game Development', 46, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (911, 'Data Structures', 46, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (912, 'Computer Graphics', 46, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (913, 'Blockchain Technology', 46, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (921, 'System Design', 47, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (922, 'System Design', 47, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (923, 'Computer Graphics', 47, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (924, 'Blockchain Technology', 47, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (925, 'Business Analytics', 47, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (926, 'Quantum Computing', 47, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (927, 'Database Systems', 47, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (928, 'Embedded Systems', 47, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (929, 'Computer Networks', 47, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (930, 'Introduction to Programming', 47, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (931, 'Statistical Analysis', 47, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (932, 'Business Analytics', 47, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (933, 'Computer Architecture', 47, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (934, 'Data Structures', 47, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (935, 'Parallel Computing', 47, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (941, 'Data Mining', 48, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (942, 'Digital Marketing', 48, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (943, 'Digital Marketing', 48, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (944, 'Internet of Things', 48, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (945, 'Mobile Development', 48, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (946, 'Introduction to Programming', 48, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (947, 'Artificial Intelligence', 48, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (948, 'Computer Networks', 48, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (961, 'Advanced Mathematics', 49, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (962, 'Web Development', 49, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (963, 'Internet of Things', 49, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (964, 'Computer Networks', 49, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (965, 'Operating Systems', 49, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (966, 'Natural Language Processing', 49, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (967, 'Computer Graphics', 49, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (968, 'Digital Marketing', 49, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (969, 'Algorithms', 49, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (970, 'Cloud Computing', 49, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (981, 'Machine Learning', 50, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (982, 'Cybersecurity Fundamentals', 50, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (983, 'Machine Learning', 50, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (984, 'Robotics', 50, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (985, 'Mobile Development', 50, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (986, 'Statistical Analysis', 50, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (987, 'Digital Marketing', 50, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (988, 'Operating Systems', 50, 2);

COMMIT;

SET FOREIGN_KEY_CHECKS=1;
