-- Generated on 2025-01-08 17:11:51
-- COMMIT EVERY 1000 ROWS

SET FOREIGN_KEY_CHECKS=0;

INSERT INTO college_class (class_id, name, college_id, semester) VALUES (1, 'Robotics', 1, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (2, 'Robotics', 1, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (3, 'Business Analytics', 1, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (4, 'Cybersecurity Fundamentals', 1, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (5, 'Parallel Computing', 1, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (6, 'Parallel Computing', 1, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (7, 'Digital Marketing', 1, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (8, 'Blockchain Technology', 1, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (21, 'Introduction to Programming', 2, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (22, 'Mobile Development', 2, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (23, 'Advanced Mathematics', 2, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (24, 'Blockchain Technology', 2, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (25, 'Internet of Things', 2, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (26, 'Quantum Computing', 2, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (27, 'Web Development', 2, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (28, 'Statistical Analysis', 2, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (29, 'Cybersecurity Fundamentals', 2, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (30, 'System Design', 2, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (31, 'Data Mining', 2, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (32, 'Internet of Things', 2, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (41, 'Artificial Intelligence', 3, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (42, 'Computer Graphics', 3, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (43, 'System Design', 3, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (44, 'Introduction to Programming', 3, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (45, 'Web Development', 3, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (46, 'Mobile Development', 3, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (47, 'Cloud Computing', 3, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (48, 'Data Structures', 3, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (49, 'Data Mining', 3, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (50, 'System Design', 3, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (51, 'Mobile Development', 3, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (52, 'Embedded Systems', 3, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (53, 'Cybersecurity Fundamentals', 3, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (54, 'Cybersecurity Fundamentals', 3, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (55, 'Web Development', 3, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (61, 'Computer Graphics', 4, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (62, 'Cybersecurity Fundamentals', 4, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (63, 'Data Mining', 4, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (64, 'Cloud Computing', 4, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (65, 'Computer Networks', 4, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (66, 'Business Analytics', 4, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (67, 'Cloud Computing', 4, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (68, 'Embedded Systems', 4, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (69, 'Business Analytics', 4, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (70, 'Algorithms', 4, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (71, 'Software Engineering', 4, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (72, 'Data Mining', 4, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (73, 'Statistical Analysis', 4, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (74, 'Digital Marketing', 4, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (81, 'Project Management', 5, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (82, 'Parallel Computing', 5, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (83, 'Statistical Analysis', 5, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (84, 'Natural Language Processing', 5, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (85, 'Machine Learning', 5, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (86, 'System Design', 5, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (87, 'Computer Graphics', 5, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (88, 'Database Systems', 5, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (101, 'Introduction to Programming', 6, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (102, 'Algorithms', 6, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (103, 'Robotics', 6, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (104, 'Introduction to Programming', 6, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (105, 'Database Systems', 6, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (106, 'Embedded Systems', 6, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (107, 'Mobile Development', 6, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (108, 'Computer Graphics', 6, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (109, 'Algorithms', 6, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (110, 'System Design', 6, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (111, 'Quantum Computing', 6, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (121, 'Advanced Mathematics', 7, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (122, 'Machine Learning', 7, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (123, 'Artificial Intelligence', 7, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (124, 'Computer Graphics', 7, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (125, 'Computer Networks', 7, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (126, 'Statistical Analysis', 7, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (127, 'System Design', 7, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (128, 'Operating Systems', 7, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (129, 'Data Structures', 7, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (130, 'Internet of Things', 7, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (131, 'Statistical Analysis', 7, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (132, 'Web Development', 7, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (141, 'Computer Graphics', 8, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (142, 'Digital Marketing', 8, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (143, 'Statistical Analysis', 8, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (144, 'Mobile Development', 8, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (145, 'Computer Architecture', 8, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (146, 'Web Development', 8, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (147, 'Software Engineering', 8, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (148, 'Project Management', 8, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (149, 'Robotics', 8, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (161, 'Operating Systems', 9, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (162, 'Mobile Development', 9, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (163, 'Business Analytics', 9, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (164, 'Game Development', 9, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (165, 'Data Structures', 9, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (166, 'System Design', 9, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (167, 'Advanced Mathematics', 9, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (168, 'Game Development', 9, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (169, 'Computer Networks', 9, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (170, 'Database Systems', 9, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (171, 'Digital Marketing', 9, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (172, 'Software Engineering', 9, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (173, 'Computer Networks', 9, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (174, 'Statistical Analysis', 9, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (175, 'Advanced Mathematics', 9, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (181, 'Business Analytics', 10, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (182, 'Computer Graphics', 10, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (183, 'Natural Language Processing', 10, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (184, 'Internet of Things', 10, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (185, 'Mobile Development', 10, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (186, 'Cybersecurity Fundamentals', 10, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (187, 'Web Development', 10, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (188, 'Blockchain Technology', 10, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (189, 'Mobile Development', 10, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (190, 'Mobile Development', 10, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (191, 'System Design', 10, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (201, 'Data Structures', 11, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (202, 'Computer Networks', 11, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (203, 'Advanced Mathematics', 11, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (204, 'Computer Networks', 11, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (205, 'Statistical Analysis', 11, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (206, 'Cybersecurity Fundamentals', 11, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (207, 'Software Engineering', 11, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (208, 'Natural Language Processing', 11, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (209, 'Cloud Computing', 11, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (210, 'Computer Networks', 11, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (211, 'Mobile Development', 11, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (212, 'Game Development', 11, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (213, 'Database Systems', 11, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (214, 'Statistical Analysis', 11, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (221, 'Statistical Analysis', 12, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (222, 'System Design', 12, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (223, 'Quantum Computing', 12, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (224, 'Artificial Intelligence', 12, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (225, 'Data Structures', 12, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (226, 'Operating Systems', 12, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (227, 'Digital Marketing', 12, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (228, 'Data Mining', 12, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (229, 'Blockchain Technology', 12, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (241, 'Cloud Computing', 13, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (242, 'Software Engineering', 13, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (243, 'Computer Graphics', 13, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (244, 'Parallel Computing', 13, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (245, 'Advanced Mathematics', 13, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (246, 'Game Development', 13, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (247, 'Algorithms', 13, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (248, 'Algorithms', 13, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (249, 'System Design', 13, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (250, 'Statistical Analysis', 13, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (251, 'Computer Architecture', 13, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (252, 'Parallel Computing', 13, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (253, 'Embedded Systems', 13, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (254, 'Introduction to Programming', 13, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (261, 'Digital Marketing', 14, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (262, 'Business Analytics', 14, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (263, 'Software Engineering', 14, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (264, 'Operating Systems', 14, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (265, 'Natural Language Processing', 14, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (266, 'System Design', 14, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (267, 'Mobile Development', 14, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (268, 'Statistical Analysis', 14, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (269, 'Mobile Development', 14, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (270, 'Data Structures', 14, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (271, 'Project Management', 14, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (272, 'Algorithms', 14, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (273, 'Data Mining', 14, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (281, 'Robotics', 15, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (282, 'Database Systems', 15, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (283, 'Advanced Mathematics', 15, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (284, 'Machine Learning', 15, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (285, 'Cloud Computing', 15, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (286, 'Advanced Mathematics', 15, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (287, 'Project Management', 15, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (288, 'Blockchain Technology', 15, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (289, 'Blockchain Technology', 15, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (290, 'Computer Architecture', 15, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (291, 'Algorithms', 15, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (292, 'Quantum Computing', 15, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (293, 'Web Development', 15, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (301, 'Digital Marketing', 16, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (302, 'Computer Networks', 16, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (303, 'Internet of Things', 16, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (304, 'Introduction to Programming', 16, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (305, 'Algorithms', 16, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (306, 'Business Analytics', 16, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (307, 'Introduction to Programming', 16, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (308, 'Mobile Development', 16, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (309, 'Mobile Development', 16, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (310, 'Cloud Computing', 16, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (311, 'Internet of Things', 16, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (321, 'Digital Marketing', 17, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (322, 'Cloud Computing', 17, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (323, 'Parallel Computing', 17, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (324, 'Data Structures', 17, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (325, 'Data Mining', 17, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (326, 'Game Development', 17, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (327, 'Artificial Intelligence', 17, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (328, 'Introduction to Programming', 17, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (329, 'Robotics', 17, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (330, 'Computer Architecture', 17, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (331, 'Game Development', 17, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (332, 'Web Development', 17, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (333, 'Introduction to Programming', 17, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (334, 'Web Development', 17, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (335, 'Database Systems', 17, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (341, 'Parallel Computing', 18, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (342, 'Mobile Development', 18, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (343, 'Operating Systems', 18, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (344, 'Artificial Intelligence', 18, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (345, 'Statistical Analysis', 18, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (346, 'Data Structures', 18, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (347, 'Parallel Computing', 18, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (348, 'Internet of Things', 18, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (349, 'Introduction to Programming', 18, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (361, 'Parallel Computing', 19, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (362, 'Parallel Computing', 19, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (363, 'Robotics', 19, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (364, 'Digital Marketing', 19, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (365, 'Operating Systems', 19, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (366, 'Database Systems', 19, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (367, 'Operating Systems', 19, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (368, 'Computer Architecture', 19, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (369, 'Natural Language Processing', 19, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (370, 'Machine Learning', 19, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (371, 'Data Structures', 19, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (381, 'Blockchain Technology', 20, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (382, 'Cybersecurity Fundamentals', 20, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (383, 'Cybersecurity Fundamentals', 20, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (384, 'Advanced Mathematics', 20, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (385, 'Statistical Analysis', 20, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (386, 'Data Structures', 20, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (387, 'Natural Language Processing', 20, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (388, 'Embedded Systems', 20, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (389, 'Operating Systems', 20, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (390, 'Web Development', 20, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (391, 'Data Structures', 20, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (392, 'Business Analytics', 20, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (393, 'Cloud Computing', 20, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (394, 'Advanced Mathematics', 20, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (401, 'Internet of Things', 21, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (402, 'Statistical Analysis', 21, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (403, 'Database Systems', 21, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (404, 'Machine Learning', 21, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (405, 'Blockchain Technology', 21, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (406, 'Web Development', 21, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (407, 'Software Engineering', 21, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (408, 'Machine Learning', 21, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (421, 'Data Structures', 22, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (422, 'Artificial Intelligence', 22, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (423, 'Internet of Things', 22, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (424, 'Computer Architecture', 22, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (425, 'Embedded Systems', 22, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (426, 'Artificial Intelligence', 22, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (427, 'Machine Learning', 22, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (428, 'Machine Learning', 22, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (441, 'Computer Architecture', 23, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (442, 'Internet of Things', 23, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (443, 'Database Systems', 23, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (444, 'Business Analytics', 23, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (445, 'Robotics', 23, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (446, 'Operating Systems', 23, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (447, 'System Design', 23, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (448, 'Advanced Mathematics', 23, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (449, 'Cloud Computing', 23, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (461, 'Algorithms', 24, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (462, 'Database Systems', 24, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (463, 'Parallel Computing', 24, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (464, 'Parallel Computing', 24, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (465, 'Introduction to Programming', 24, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (466, 'Software Engineering', 24, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (467, 'Computer Graphics', 24, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (468, 'Machine Learning', 24, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (469, 'Parallel Computing', 24, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (470, 'Database Systems', 24, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (471, 'Advanced Mathematics', 24, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (472, 'Robotics', 24, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (473, 'System Design', 24, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (474, 'Introduction to Programming', 24, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (481, 'Algorithms', 25, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (482, 'Computer Networks', 25, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (483, 'Business Analytics', 25, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (484, 'Embedded Systems', 25, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (485, 'Software Engineering', 25, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (486, 'Mobile Development', 25, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (487, 'Data Structures', 25, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (488, 'Business Analytics', 25, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (489, 'Digital Marketing', 25, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (490, 'Machine Learning', 25, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (501, 'Data Mining', 26, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (502, 'Quantum Computing', 26, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (503, 'Natural Language Processing', 26, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (504, 'Software Engineering', 26, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (505, 'Algorithms', 26, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (506, 'Business Analytics', 26, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (507, 'Algorithms', 26, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (508, 'Quantum Computing', 26, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (509, 'Robotics', 26, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (510, 'Blockchain Technology', 26, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (511, 'Computer Architecture', 26, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (512, 'Computer Graphics', 26, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (513, 'Artificial Intelligence', 26, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (521, 'Parallel Computing', 27, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (522, 'Parallel Computing', 27, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (523, 'Computer Networks', 27, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (524, 'Cloud Computing', 27, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (525, 'Introduction to Programming', 27, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (526, 'Computer Architecture', 27, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (527, 'Embedded Systems', 27, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (528, 'Robotics', 27, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (529, 'Quantum Computing', 27, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (530, 'Natural Language Processing', 27, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (531, 'Algorithms', 27, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (541, 'Advanced Mathematics', 28, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (542, 'Advanced Mathematics', 28, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (543, 'Project Management', 28, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (544, 'Blockchain Technology', 28, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (545, 'Computer Architecture', 28, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (546, 'Internet of Things', 28, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (547, 'Quantum Computing', 28, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (548, 'Machine Learning', 28, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (549, 'Advanced Mathematics', 28, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (561, 'Computer Graphics', 29, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (562, 'Digital Marketing', 29, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (563, 'Business Analytics', 29, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (564, 'Algorithms', 29, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (565, 'System Design', 29, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (566, 'Statistical Analysis', 29, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (567, 'Operating Systems', 29, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (568, 'Robotics', 29, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (569, 'Artificial Intelligence', 29, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (570, 'Advanced Mathematics', 29, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (571, 'Internet of Things', 29, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (572, 'Cybersecurity Fundamentals', 29, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (573, 'Mobile Development', 29, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (574, 'Machine Learning', 29, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (581, 'Blockchain Technology', 30, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (582, 'Internet of Things', 30, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (583, 'Web Development', 30, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (584, 'Advanced Mathematics', 30, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (585, 'Web Development', 30, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (586, 'Robotics', 30, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (587, 'Blockchain Technology', 30, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (588, 'Mobile Development', 30, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (589, 'Software Engineering', 30, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (601, 'Introduction to Programming', 31, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (602, 'Digital Marketing', 31, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (603, 'Statistical Analysis', 31, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (604, 'Game Development', 31, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (605, 'Artificial Intelligence', 31, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (606, 'Mobile Development', 31, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (607, 'Cybersecurity Fundamentals', 31, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (608, 'Natural Language Processing', 31, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (609, 'Mobile Development', 31, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (621, 'Computer Networks', 32, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (622, 'Natural Language Processing', 32, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (623, 'Cloud Computing', 32, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (624, 'Computer Networks', 32, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (625, 'Project Management', 32, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (626, 'Data Structures', 32, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (627, 'Game Development', 32, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (628, 'Data Mining', 32, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (629, 'Data Structures', 32, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (630, 'Statistical Analysis', 32, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (631, 'Internet of Things', 32, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (632, 'Web Development', 32, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (633, 'Blockchain Technology', 32, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (634, 'Computer Graphics', 32, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (641, 'Algorithms', 33, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (642, 'Mobile Development', 33, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (643, 'Project Management', 33, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (644, 'Blockchain Technology', 33, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (645, 'Game Development', 33, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (646, 'Business Analytics', 33, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (647, 'Parallel Computing', 33, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (648, 'Advanced Mathematics', 33, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (649, 'Mobile Development', 33, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (650, 'Introduction to Programming', 33, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (651, 'Advanced Mathematics', 33, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (661, 'Project Management', 34, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (662, 'Software Engineering', 34, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (663, 'Computer Graphics', 34, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (664, 'Advanced Mathematics', 34, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (665, 'Artificial Intelligence', 34, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (666, 'Computer Networks', 34, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (667, 'Mobile Development', 34, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (668, 'Cloud Computing', 34, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (669, 'Project Management', 34, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (670, 'Introduction to Programming', 34, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (671, 'Computer Networks', 34, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (672, 'Machine Learning', 34, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (673, 'Computer Graphics', 34, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (681, 'Computer Networks', 35, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (682, 'Mobile Development', 35, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (683, 'Blockchain Technology', 35, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (684, 'Algorithms', 35, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (685, 'Cybersecurity Fundamentals', 35, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (686, 'Cloud Computing', 35, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (687, 'Computer Graphics', 35, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (688, 'Mobile Development', 35, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (689, 'Robotics', 35, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (690, 'System Design', 35, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (691, 'Computer Graphics', 35, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (692, 'Computer Networks', 35, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (701, 'Internet of Things', 36, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (702, 'Statistical Analysis', 36, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (703, 'Quantum Computing', 36, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (704, 'Computer Graphics', 36, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (705, 'Machine Learning', 36, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (706, 'Statistical Analysis', 36, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (707, 'Computer Graphics', 36, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (708, 'Web Development', 36, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (709, 'Introduction to Programming', 36, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (710, 'Project Management', 36, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (711, 'Statistical Analysis', 36, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (721, 'Data Structures', 37, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (722, 'Machine Learning', 37, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (723, 'Data Mining', 37, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (724, 'Robotics', 37, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (725, 'Embedded Systems', 37, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (726, 'Natural Language Processing', 37, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (727, 'Business Analytics', 37, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (728, 'Parallel Computing', 37, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (741, 'Database Systems', 38, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (742, 'System Design', 38, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (743, 'Web Development', 38, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (744, 'Advanced Mathematics', 38, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (745, 'Data Structures', 38, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (746, 'Embedded Systems', 38, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (747, 'Statistical Analysis', 38, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (748, 'Quantum Computing', 38, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (761, 'Parallel Computing', 39, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (762, 'Artificial Intelligence', 39, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (763, 'Software Engineering', 39, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (764, 'Computer Graphics', 39, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (765, 'Mobile Development', 39, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (766, 'Cybersecurity Fundamentals', 39, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (767, 'System Design', 39, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (768, 'Internet of Things', 39, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (769, 'Cybersecurity Fundamentals', 39, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (770, 'Mobile Development', 39, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (771, 'Algorithms', 39, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (772, 'Computer Architecture', 39, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (781, 'Data Structures', 40, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (782, 'Computer Architecture', 40, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (783, 'Statistical Analysis', 40, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (784, 'Computer Architecture', 40, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (785, 'System Design', 40, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (786, 'Digital Marketing', 40, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (787, 'Natural Language Processing', 40, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (788, 'Blockchain Technology', 40, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (789, 'Parallel Computing', 40, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (790, 'Digital Marketing', 40, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (791, 'Operating Systems', 40, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (792, 'Cloud Computing', 40, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (793, 'Quantum Computing', 40, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (801, 'Computer Architecture', 41, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (802, 'Digital Marketing', 41, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (803, 'Embedded Systems', 41, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (804, 'Introduction to Programming', 41, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (805, 'Embedded Systems', 41, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (806, 'Data Mining', 41, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (807, 'Project Management', 41, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (808, 'Natural Language Processing', 41, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (809, 'Database Systems', 41, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (810, 'Mobile Development', 41, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (811, 'Machine Learning', 41, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (821, 'Cybersecurity Fundamentals', 42, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (822, 'Artificial Intelligence', 42, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (823, 'Advanced Mathematics', 42, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (824, 'Parallel Computing', 42, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (825, 'Blockchain Technology', 42, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (826, 'Quantum Computing', 42, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (827, 'Digital Marketing', 42, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (828, 'Computer Architecture', 42, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (841, 'Introduction to Programming', 43, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (842, 'Natural Language Processing', 43, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (843, 'Data Structures', 43, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (844, 'Computer Networks', 43, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (845, 'Operating Systems', 43, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (846, 'Embedded Systems', 43, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (847, 'Blockchain Technology', 43, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (848, 'Machine Learning', 43, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (849, 'Internet of Things', 43, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (850, 'Project Management', 43, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (851, 'Machine Learning', 43, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (852, 'Operating Systems', 43, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (853, 'Game Development', 43, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (854, 'Robotics', 43, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (861, 'Database Systems', 44, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (862, 'System Design', 44, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (863, 'Data Structures', 44, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (864, 'Web Development', 44, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (865, 'Internet of Things', 44, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (866, 'Digital Marketing', 44, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (867, 'Mobile Development', 44, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (868, 'Computer Networks', 44, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (869, 'Machine Learning', 44, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (870, 'Artificial Intelligence', 44, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (881, 'Data Structures', 45, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (882, 'Artificial Intelligence', 45, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (883, 'Cloud Computing', 45, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (884, 'Blockchain Technology', 45, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (885, 'Natural Language Processing', 45, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (886, 'Introduction to Programming', 45, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (887, 'Project Management', 45, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (888, 'Introduction to Programming', 45, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (901, 'Internet of Things', 46, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (902, 'Data Mining', 46, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (903, 'Natural Language Processing', 46, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (904, 'Software Engineering', 46, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (905, 'Game Development', 46, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (906, 'Cloud Computing', 46, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (907, 'Project Management', 46, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (908, 'System Design', 46, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (909, 'Computer Networks', 46, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (910, 'Robotics', 46, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (911, 'Software Engineering', 46, 1);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (912, 'Blockchain Technology', 46, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (913, 'Cybersecurity Fundamentals', 46, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (914, 'Computer Architecture', 46, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (915, 'Artificial Intelligence', 46, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (921, 'Introduction to Programming', 47, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (922, 'Web Development', 47, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (923, 'Algorithms', 47, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (924, 'Computer Graphics', 47, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (925, 'Statistical Analysis', 47, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (926, 'Natural Language Processing', 47, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (927, 'Internet of Things', 47, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (928, 'Internet of Things', 47, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (929, 'Advanced Mathematics', 47, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (930, 'Project Management', 47, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (931, 'Robotics', 47, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (932, 'Robotics', 47, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (933, 'Cloud Computing', 47, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (941, 'Computer Architecture', 48, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (942, 'Machine Learning', 48, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (943, 'Project Management', 48, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (944, 'Business Analytics', 48, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (945, 'Software Engineering', 48, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (946, 'Computer Networks', 48, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (947, 'Computer Graphics', 48, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (948, 'System Design', 48, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (949, 'Cloud Computing', 48, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (950, 'Mobile Development', 48, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (951, 'Artificial Intelligence', 48, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (952, 'Artificial Intelligence', 48, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (953, 'Blockchain Technology', 48, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (961, 'Embedded Systems', 49, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (962, 'Data Structures', 49, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (963, 'Cloud Computing', 49, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (964, 'Algorithms', 49, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (965, 'Data Mining', 49, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (966, 'Quantum Computing', 49, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (967, 'Embedded Systems', 49, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (968, 'Machine Learning', 49, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (969, 'Artificial Intelligence', 49, 5);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (970, 'Parallel Computing', 49, 2);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (971, 'Artificial Intelligence', 49, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (981, 'Game Development', 50, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (982, 'Cybersecurity Fundamentals', 50, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (983, 'Computer Networks', 50, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (984, 'Artificial Intelligence', 50, 6);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (985, 'Web Development', 50, 3);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (986, 'Database Systems', 50, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (987, 'Internet of Things', 50, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (988, 'Digital Marketing', 50, 7);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (989, 'Data Mining', 50, 8);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (990, 'Digital Marketing', 50, 4);
INSERT INTO college_class (class_id, name, college_id, semester) VALUES (991, 'Embedded Systems', 50, 8);

COMMIT;

SET FOREIGN_KEY_CHECKS=1;
