INSERT INTO rooms (name, place_limit) VALUES ('The Parallel Center', 11);
INSERT INTO rooms (name, place_limit) VALUES ('Intelligent Hall 867', 32);
INSERT INTO rooms (name, place_limit) VALUES ('Syntactic Engineering Center', 17);
INSERT INTO rooms (name, place_limit) VALUES ('Computing Facility', 86);
INSERT INTO rooms (name, place_limit) VALUES ('Media Room', 82);
INSERT INTO rooms (name, place_limit) VALUES ('Syntactic Technology Hall', 98);
INSERT INTO rooms (name, place_limit) VALUES ('The Cyber Center', 69);
INSERT INTO rooms (name, place_limit) VALUES ('Quantum Chamber 296', 94);
INSERT INTO rooms (name, place_limit) VALUES ('The Semantic Lab', 58);
INSERT INTO rooms (name, place_limit) VALUES ('The Algorithmic Facility', 27);
INSERT INTO rooms (name, place_limit) VALUES ('Intelligent Innovation Facility', 89);
INSERT INTO rooms (name, place_limit) VALUES ('Technology Room', 71);
INSERT INTO rooms (name, place_limit) VALUES ('Autonomous Engineering Facility', 53);
INSERT INTO rooms (name, place_limit) VALUES ('Modular Room 961', 38);
INSERT INTO rooms (name, place_limit) VALUES ('The Algorithmic Hall', 24);
INSERT INTO rooms (name, place_limit) VALUES ('Autonomous Engineering Chamber', 54);
INSERT INTO rooms (name, place_limit) VALUES ('Digital Engineering Chamber', 84);
INSERT INTO rooms (name, place_limit) VALUES ('Learning Room', 77);
INSERT INTO rooms (name, place_limit) VALUES ('Cognitive Center 922', 96);
INSERT INTO rooms (name, place_limit) VALUES ('Semantic Computing Hub', 32);
INSERT INTO rooms (name, place_limit) VALUES ('Robotics Room', 28);
INSERT INTO rooms (name, place_limit) VALUES ('Cognitive Facility 535', 61);
INSERT INTO rooms (name, place_limit) VALUES ('Encrypted Robotics Room', 31);
INSERT INTO rooms (name, place_limit) VALUES ('Algorithmic Center 128', 27);
INSERT INTO rooms (name, place_limit) VALUES ('Intelligent Technology Hub', 21);
INSERT INTO rooms (name, place_limit) VALUES ('Intelligent Robotics Chamber', 25);
INSERT INTO rooms (name, place_limit) VALUES ('Design Hall', 75);
INSERT INTO rooms (name, place_limit) VALUES ('Design Facility', 48);
INSERT INTO rooms (name, place_limit) VALUES ('The Intelligent Room', 66);
INSERT INTO rooms (name, place_limit) VALUES ('Binary Hall 587', 62);
INSERT INTO rooms (name, place_limit) VALUES ('The Decentralized Center', 86);
INSERT INTO rooms (name, place_limit) VALUES ('The Parallel Suite', 95);
INSERT INTO rooms (name, place_limit) VALUES ('Cyber Hub 447', 61);
INSERT INTO rooms (name, place_limit) VALUES ('Logical Projects Suite', 79);
INSERT INTO rooms (name, place_limit) VALUES ('The Syntactic Chamber', 45);
INSERT INTO rooms (name, place_limit) VALUES ('The Syntactic Hub', 36);
INSERT INTO rooms (name, place_limit) VALUES ('Cyber Media Room', 61);
INSERT INTO rooms (name, place_limit) VALUES ('Optimized Center 594', 53);
INSERT INTO rooms (name, place_limit) VALUES ('Data-Driven Engineering Room', 41);
INSERT INTO rooms (name, place_limit) VALUES ('The Semantic Center', 76);
INSERT INTO rooms (name, place_limit) VALUES ('Quantum Hall 559', 33);
INSERT INTO rooms (name, place_limit) VALUES ('Semantic Technology Lab', 52);
INSERT INTO rooms (name, place_limit) VALUES ('Syntactic Arts Lab', 32);
INSERT INTO rooms (name, place_limit) VALUES ('Scalable Analytics Suite', 12);
INSERT INTO rooms (name, place_limit) VALUES ('Quantum Virtual Hub', 75);
INSERT INTO rooms (name, place_limit) VALUES ('Media Hub', 46);
INSERT INTO rooms (name, place_limit) VALUES ('Development Suite', 16);
INSERT INTO rooms (name, place_limit) VALUES ('Algorithmic Hub 690', 41);
INSERT INTO rooms (name, place_limit) VALUES ('The Algorithmic Lab', 39);
INSERT INTO rooms (name, place_limit) VALUES ('Logical Suite 186', 73);
