INSERT INTO countries (name) VALUES ('Poland');
INSERT INTO countries (name) VALUES ('Germany');
INSERT INTO countries (name) VALUES ('France');
INSERT INTO countries (name) VALUES ('Belgium');
INSERT INTO countries (name) VALUES ('Netherlands');
INSERT INTO countries (name) VALUES ('Czech Republic');
INSERT INTO countries (name) VALUES ('Slovakia');
INSERT INTO countries (name) VALUES ('Hungary');
INSERT INTO countries (name) VALUES ('Austria');
INSERT INTO countries (name) VALUES ('Switzerland');
INSERT INTO countries (name) VALUES ('Italy');
INSERT INTO countries (name) VALUES ('Sweden');
INSERT INTO countries (name) VALUES ('Denmark');
INSERT INTO countries (name) VALUES ('Finland');
INSERT INTO countries (name) VALUES ('Norway');
