-- Generated on 2025-01-09 00:35:37
-- COMMIT EVERY 1000 ROWS

SET FOREIGN_KEY_CHECKS=0;

INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Database Management', 1);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Workshop', 1);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Project', 1);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Lab', 1);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Database Management', 1);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Case Studies', 1);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Database Management', 1);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Workshop', 1);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Project', 2);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Lab', 2);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied DevOps Practices', 2);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical DevOps Practices', 2);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Business Analytics', 3);
INSERT INTO course_class ( name, course_id) VALUES ( 'Business Analytics Project', 3);
INSERT INTO course_class ( name, course_id) VALUES ( 'Business Analytics Lab', 3);
INSERT INTO course_class ( name, course_id) VALUES ( 'Business Analytics Seminar', 3);
INSERT INTO course_class ( name, course_id) VALUES ( 'UI/UX Design Seminar', 4);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in UI/UX Design', 4);
INSERT INTO course_class ( name, course_id) VALUES ( 'UI/UX Design Lab', 4);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Project', 5);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Project Management', 5);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Seminar', 5);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Seminar', 5);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Workshop', 5);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Project Management', 5);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Machine Learning Basics', 6);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Machine Learning Basics', 6);
INSERT INTO course_class ( name, course_id) VALUES ( 'Machine Learning Basics Seminar', 6);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Machine Learning Basics', 6);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Software Architecture', 7);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Software Architecture', 7);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Software Architecture', 7);
INSERT INTO course_class ( name, course_id) VALUES ( 'Cloud Computing Workshop', 8);
INSERT INTO course_class ( name, course_id) VALUES ( 'Cloud Computing Workshop', 8);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Cloud Computing', 8);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Cloud Computing', 8);
INSERT INTO course_class ( name, course_id) VALUES ( 'Cloud Computing Seminar', 8);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Cloud Computing', 8);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Data Analytics', 9);
INSERT INTO course_class ( name, course_id) VALUES ( 'Data Analytics Seminar', 9);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Data Analytics', 9);
INSERT INTO course_class ( name, course_id) VALUES ( 'Data Analytics Project', 9);
INSERT INTO course_class ( name, course_id) VALUES ( 'Data Analytics Workshop', 9);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Machine Learning Basics', 10);
INSERT INTO course_class ( name, course_id) VALUES ( 'Machine Learning Basics Lab', 10);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Machine Learning Basics', 10);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Machine Learning Basics', 10);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Machine Learning Basics', 10);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Network Security', 11);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Project', 11);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Workshop', 11);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Network Security', 11);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Network Security', 11);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Network Security', 11);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Data Science Fundamentals', 12);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Data Science Fundamentals', 12);
INSERT INTO course_class ( name, course_id) VALUES ( 'Data Science Fundamentals Workshop', 12);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Data Science Fundamentals', 12);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Project', 13);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Seminar', 13);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Seminar', 13);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Database Management', 13);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Database Management', 13);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Database Management', 13);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Database Management', 13);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Project', 13);
INSERT INTO course_class ( name, course_id) VALUES ( 'Web Technologies Lab', 14);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Web Technologies', 14);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Web Technologies', 14);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Case Studies', 15);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Network Security', 15);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Seminar', 15);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Seminar', 15);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Network Security', 15);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Seminar', 15);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Lab', 15);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Case Studies', 15);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical DevOps Practices', 16);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Project', 16);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical DevOps Practices', 16);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied DevOps Practices', 16);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Seminar', 16);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Seminar', 16);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to DevOps Practices', 16);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Software Architecture', 17);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Software Architecture', 17);
INSERT INTO course_class ( name, course_id) VALUES ( 'Software Architecture Seminar', 17);
INSERT INTO course_class ( name, course_id) VALUES ( 'Software Architecture Workshop', 17);
INSERT INTO course_class ( name, course_id) VALUES ( 'Software Architecture Lab', 17);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Software Architecture', 17);
INSERT INTO course_class ( name, course_id) VALUES ( 'Quality Assurance Lab', 18);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Quality Assurance', 18);
INSERT INTO course_class ( name, course_id) VALUES ( 'Quality Assurance Seminar', 18);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Quality Assurance', 19);
INSERT INTO course_class ( name, course_id) VALUES ( 'Quality Assurance Case Studies', 19);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Quality Assurance', 19);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Quality Assurance', 19);
INSERT INTO course_class ( name, course_id) VALUES ( 'Internet of Things Lab', 20);
INSERT INTO course_class ( name, course_id) VALUES ( 'Internet of Things Project', 20);
INSERT INTO course_class ( name, course_id) VALUES ( 'Internet of Things Seminar', 20);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Internet of Things', 20);
INSERT INTO course_class ( name, course_id) VALUES ( 'Internet of Things Lab', 20);
INSERT INTO course_class ( name, course_id) VALUES ( 'Cloud Computing Seminar', 21);
INSERT INTO course_class ( name, course_id) VALUES ( 'Cloud Computing Seminar', 21);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Cloud Computing', 21);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Cloud Computing', 21);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Cloud Computing', 21);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Cloud Computing', 21);
INSERT INTO course_class ( name, course_id) VALUES ( 'Cloud Computing Seminar', 21);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Java Development', 22);
INSERT INTO course_class ( name, course_id) VALUES ( 'Java Development Workshop', 22);
INSERT INTO course_class ( name, course_id) VALUES ( 'Java Development Project', 22);
INSERT INTO course_class ( name, course_id) VALUES ( 'Java Development Workshop', 22);
INSERT INTO course_class ( name, course_id) VALUES ( 'Java Development Lab', 22);
INSERT INTO course_class ( name, course_id) VALUES ( 'Java Development Project', 22);
INSERT INTO course_class ( name, course_id) VALUES ( 'Python Programming Seminar', 23);
INSERT INTO course_class ( name, course_id) VALUES ( 'Python Programming Project', 23);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Python Programming', 23);
INSERT INTO course_class ( name, course_id) VALUES ( 'Python Programming Project', 23);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Quality Assurance', 24);
INSERT INTO course_class ( name, course_id) VALUES ( 'Quality Assurance Lab', 24);
INSERT INTO course_class ( name, course_id) VALUES ( 'Quality Assurance Project', 24);
INSERT INTO course_class ( name, course_id) VALUES ( 'Quality Assurance Project', 24);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Quality Assurance', 24);
INSERT INTO course_class ( name, course_id) VALUES ( 'Quality Assurance Project', 24);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Quality Assurance', 24);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Workshop', 25);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in DevOps Practices', 25);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Seminar', 25);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to DevOps Practices', 25);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in DevOps Practices', 25);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Project', 25);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in DevOps Practices', 25);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Agile Methodologies', 26);
INSERT INTO course_class ( name, course_id) VALUES ( 'Agile Methodologies Seminar', 26);
INSERT INTO course_class ( name, course_id) VALUES ( 'Agile Methodologies Project', 26);
INSERT INTO course_class ( name, course_id) VALUES ( 'Agile Methodologies Project', 26);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Agile Methodologies', 26);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Agile Methodologies', 26);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Seminar', 27);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Project', 27);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Project', 27);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Project', 27);
INSERT INTO course_class ( name, course_id) VALUES ( 'Network Security Case Studies', 27);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Business Analytics', 28);
INSERT INTO course_class ( name, course_id) VALUES ( 'Business Analytics Workshop', 28);
INSERT INTO course_class ( name, course_id) VALUES ( 'Business Analytics Lab', 28);
INSERT INTO course_class ( name, course_id) VALUES ( 'Business Analytics Project', 28);
INSERT INTO course_class ( name, course_id) VALUES ( 'Business Analytics Lab', 28);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Business Analytics', 28);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Business Analytics', 28);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Internet of Things', 29);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Internet of Things', 29);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Internet of Things', 29);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Internet of Things', 29);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Internet of Things', 29);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Seminar', 30);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Case Studies', 30);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Case Studies', 30);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Seminar', 30);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Cloud Computing', 31);
INSERT INTO course_class ( name, course_id) VALUES ( 'Cloud Computing Project', 31);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Cloud Computing', 31);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Lab', 32);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Database Management', 32);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Lab', 32);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Lab', 32);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Lab', 32);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Project', 32);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Workshop', 33);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Project Management', 33);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Project Management', 33);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Seminar', 33);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Project Management', 33);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Project', 33);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Project Management', 33);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Data Science Fundamentals', 34);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Data Science Fundamentals', 34);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Data Science Fundamentals', 34);
INSERT INTO course_class ( name, course_id) VALUES ( 'Data Science Fundamentals Workshop', 34);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Data Science Fundamentals', 34);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Data Science Fundamentals', 34);
INSERT INTO course_class ( name, course_id) VALUES ( 'Data Science Fundamentals Project', 34);
INSERT INTO course_class ( name, course_id) VALUES ( 'Data Science Fundamentals Project', 34);
INSERT INTO course_class ( name, course_id) VALUES ( 'Python Programming Case Studies', 35);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Python Programming', 35);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Python Programming', 35);
INSERT INTO course_class ( name, course_id) VALUES ( 'Python Programming Project', 35);
INSERT INTO course_class ( name, course_id) VALUES ( 'Python Programming Seminar', 35);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Python Programming', 35);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Python Programming', 35);
INSERT INTO course_class ( name, course_id) VALUES ( 'Web Technologies Lab', 36);
INSERT INTO course_class ( name, course_id) VALUES ( 'Web Technologies Project', 36);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Web Technologies', 36);
INSERT INTO course_class ( name, course_id) VALUES ( 'Web Technologies Workshop', 36);
INSERT INTO course_class ( name, course_id) VALUES ( 'Mobile App Development Workshop', 37);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Mobile App Development', 37);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Mobile App Development', 37);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Mobile App Development', 37);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Mobile App Development', 37);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Mobile App Development', 37);
INSERT INTO course_class ( name, course_id) VALUES ( 'Mobile App Development Project', 37);
INSERT INTO course_class ( name, course_id) VALUES ( 'Mobile App Development Project', 37);
INSERT INTO course_class ( name, course_id) VALUES ( 'Database Management Seminar', 38);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Database Management', 38);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Database Management', 38);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Database Management', 38);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Cloud Computing', 39);
INSERT INTO course_class ( name, course_id) VALUES ( 'Cloud Computing Project', 39);
INSERT INTO course_class ( name, course_id) VALUES ( 'Cloud Computing Lab', 39);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Cloud Computing', 39);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Cloud Computing', 39);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Cloud Computing', 39);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Cloud Computing', 39);
INSERT INTO course_class ( name, course_id) VALUES ( 'Python Programming Lab', 40);
INSERT INTO course_class ( name, course_id) VALUES ( 'Python Programming Project', 40);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Python Programming', 40);
INSERT INTO course_class ( name, course_id) VALUES ( 'Python Programming Workshop', 40);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Python Programming', 40);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Python Programming', 40);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Data Analytics', 41);
INSERT INTO course_class ( name, course_id) VALUES ( 'Data Analytics Seminar', 41);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Data Analytics', 41);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Data Analytics', 41);
INSERT INTO course_class ( name, course_id) VALUES ( 'Data Analytics Workshop', 41);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Business Analytics', 42);
INSERT INTO course_class ( name, course_id) VALUES ( 'Business Analytics Lab', 42);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Business Analytics', 42);
INSERT INTO course_class ( name, course_id) VALUES ( 'Business Analytics Workshop', 42);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Business Analytics', 42);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Business Analytics', 42);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Business Analytics', 42);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Business Analytics', 42);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Lab', 43);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Case Studies', 43);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Seminar', 43);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Project Management', 43);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Workshop', 43);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Case Studies', 43);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Project Management', 43);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Project', 43);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Java Development', 44);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Java Development', 44);
INSERT INTO course_class ( name, course_id) VALUES ( 'Java Development Seminar', 44);
INSERT INTO course_class ( name, course_id) VALUES ( 'Agile Methodologies Case Studies', 45);
INSERT INTO course_class ( name, course_id) VALUES ( 'Agile Methodologies Project', 45);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Agile Methodologies', 45);
INSERT INTO course_class ( name, course_id) VALUES ( 'Machine Learning Basics Lab', 46);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Machine Learning Basics', 46);
INSERT INTO course_class ( name, course_id) VALUES ( 'Special Topics in Machine Learning Basics', 46);
INSERT INTO course_class ( name, course_id) VALUES ( 'Machine Learning Basics Project', 46);
INSERT INTO course_class ( name, course_id) VALUES ( 'Machine Learning Basics Workshop', 46);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Machine Learning Basics', 46);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Machine Learning Basics', 46);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Machine Learning Basics', 46);
INSERT INTO course_class ( name, course_id) VALUES ( 'Java Development Project', 47);
INSERT INTO course_class ( name, course_id) VALUES ( 'Java Development Lab', 47);
INSERT INTO course_class ( name, course_id) VALUES ( 'Practical Java Development', 47);
INSERT INTO course_class ( name, course_id) VALUES ( 'Java Development Seminar', 47);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Lab', 48);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Project Management', 48);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Project', 48);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Case Studies', 48);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Case Studies', 48);
INSERT INTO course_class ( name, course_id) VALUES ( 'Project Management Workshop', 48);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied Project Management', 48);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Project', 49);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Seminar', 49);
INSERT INTO course_class ( name, course_id) VALUES ( 'Applied DevOps Practices', 49);
INSERT INTO course_class ( name, course_id) VALUES ( 'DevOps Practices Workshop', 49);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Machine Learning Basics', 50);
INSERT INTO course_class ( name, course_id) VALUES ( 'Machine Learning Basics Workshop', 50);
INSERT INTO course_class ( name, course_id) VALUES ( 'Introduction to Machine Learning Basics', 50);
INSERT INTO course_class ( name, course_id) VALUES ( 'Machine Learning Basics Workshop', 50);
INSERT INTO course_class ( name, course_id) VALUES ( 'Advanced Machine Learning Basics', 50);
