-- Generated on 2025-01-08 17:17:08
-- COMMIT EVERY 1000 ROWS

SET FOREIGN_KEY_CHECKS=0;

INSERT INTO course_class (class_id, name, course_id) VALUES (1, 'Advanced Project Management', 1);
INSERT INTO course_class (class_id, name, course_id) VALUES (2, 'Project Management Project', 1);
INSERT INTO course_class (class_id, name, course_id) VALUES (3, 'Project Management Project', 1);
INSERT INTO course_class (class_id, name, course_id) VALUES (4, 'Advanced Project Management', 1);
INSERT INTO course_class (class_id, name, course_id) VALUES (5, 'Project Management Seminar', 1);
INSERT INTO course_class (class_id, name, course_id) VALUES (6, 'Special Topics in Project Management', 1);
INSERT INTO course_class (class_id, name, course_id) VALUES (7, 'Project Management Project', 1);
INSERT INTO course_class (class_id, name, course_id) VALUES (8, 'Applied Software Architecture', 2);
INSERT INTO course_class (class_id, name, course_id) VALUES (9, 'Software Architecture Seminar', 2);
INSERT INTO course_class (class_id, name, course_id) VALUES (10, 'Software Architecture Lab', 2);
INSERT INTO course_class (class_id, name, course_id) VALUES (11, 'Practical Software Architecture', 2);
INSERT INTO course_class (class_id, name, course_id) VALUES (12, 'Software Architecture Seminar', 2);
INSERT INTO course_class (class_id, name, course_id) VALUES (13, 'Introduction to Software Architecture', 2);
INSERT INTO course_class (class_id, name, course_id) VALUES (14, 'Mobile App Development Project', 3);
INSERT INTO course_class (class_id, name, course_id) VALUES (15, 'Mobile App Development Seminar', 3);
INSERT INTO course_class (class_id, name, course_id) VALUES (16, 'Special Topics in Mobile App Development', 3);
INSERT INTO course_class (class_id, name, course_id) VALUES (17, 'Special Topics in Mobile App Development', 3);
INSERT INTO course_class (class_id, name, course_id) VALUES (18, 'Mobile App Development Case Studies', 3);
INSERT INTO course_class (class_id, name, course_id) VALUES (19, 'Mobile App Development Seminar', 3);
INSERT INTO course_class (class_id, name, course_id) VALUES (20, 'Applied Mobile App Development', 3);
INSERT INTO course_class (class_id, name, course_id) VALUES (21, 'Mobile App Development Workshop', 3);
INSERT INTO course_class (class_id, name, course_id) VALUES (22, 'Applied Python Programming', 4);
INSERT INTO course_class (class_id, name, course_id) VALUES (23, 'Python Programming Lab', 4);
INSERT INTO course_class (class_id, name, course_id) VALUES (24, 'Special Topics in Python Programming', 4);
INSERT INTO course_class (class_id, name, course_id) VALUES (25, 'Python Programming Lab', 4);
INSERT INTO course_class (class_id, name, course_id) VALUES (26, 'Practical Python Programming', 4);
INSERT INTO course_class (class_id, name, course_id) VALUES (27, 'Python Programming Seminar', 4);
INSERT INTO course_class (class_id, name, course_id) VALUES (28, 'Python Programming Seminar', 4);
INSERT INTO course_class (class_id, name, course_id) VALUES (29, 'Applied Python Programming', 4);
INSERT INTO course_class (class_id, name, course_id) VALUES (30, 'Applied Artificial Intelligence', 5);
INSERT INTO course_class (class_id, name, course_id) VALUES (31, 'Advanced Artificial Intelligence', 5);
INSERT INTO course_class (class_id, name, course_id) VALUES (32, 'Advanced Artificial Intelligence', 5);
INSERT INTO course_class (class_id, name, course_id) VALUES (33, 'Introduction to Artificial Intelligence', 5);
INSERT INTO course_class (class_id, name, course_id) VALUES (34, 'Artificial Intelligence Lab', 5);
INSERT INTO course_class (class_id, name, course_id) VALUES (35, 'Artificial Intelligence Workshop', 5);
INSERT INTO course_class (class_id, name, course_id) VALUES (36, 'Applied Artificial Intelligence', 5);
INSERT INTO course_class (class_id, name, course_id) VALUES (37, 'Introduction to Quality Assurance', 6);
INSERT INTO course_class (class_id, name, course_id) VALUES (38, 'Introduction to Quality Assurance', 6);
INSERT INTO course_class (class_id, name, course_id) VALUES (39, 'Special Topics in Quality Assurance', 6);
INSERT INTO course_class (class_id, name, course_id) VALUES (40, 'Introduction to Quality Assurance', 6);
INSERT INTO course_class (class_id, name, course_id) VALUES (41, 'Advanced Machine Learning Basics', 7);
INSERT INTO course_class (class_id, name, course_id) VALUES (42, 'Machine Learning Basics Seminar', 7);
INSERT INTO course_class (class_id, name, course_id) VALUES (43, 'Applied Machine Learning Basics', 7);
INSERT INTO course_class (class_id, name, course_id) VALUES (44, 'Machine Learning Basics Seminar', 7);
INSERT INTO course_class (class_id, name, course_id) VALUES (45, 'Practical Machine Learning Basics', 7);
INSERT INTO course_class (class_id, name, course_id) VALUES (46, 'Machine Learning Basics Workshop', 7);
INSERT INTO course_class (class_id, name, course_id) VALUES (47, 'Special Topics in Machine Learning Basics', 7);
INSERT INTO course_class (class_id, name, course_id) VALUES (48, 'Cloud Computing Lab', 8);
INSERT INTO course_class (class_id, name, course_id) VALUES (49, 'Advanced Cloud Computing', 8);
INSERT INTO course_class (class_id, name, course_id) VALUES (50, 'Introduction to Cloud Computing', 8);
INSERT INTO course_class (class_id, name, course_id) VALUES (51, 'Cloud Computing Case Studies', 8);
INSERT INTO course_class (class_id, name, course_id) VALUES (52, 'Applied Cloud Computing', 8);
INSERT INTO course_class (class_id, name, course_id) VALUES (53, 'Advanced Agile Methodologies', 9);
INSERT INTO course_class (class_id, name, course_id) VALUES (54, 'Introduction to Agile Methodologies', 9);
INSERT INTO course_class (class_id, name, course_id) VALUES (55, 'Applied Agile Methodologies', 9);
INSERT INTO course_class (class_id, name, course_id) VALUES (56, 'Special Topics in Agile Methodologies', 9);
INSERT INTO course_class (class_id, name, course_id) VALUES (57, 'Agile Methodologies Workshop', 9);
INSERT INTO course_class (class_id, name, course_id) VALUES (58, 'Applied Agile Methodologies', 9);
INSERT INTO course_class (class_id, name, course_id) VALUES (59, 'Practical Quality Assurance', 10);
INSERT INTO course_class (class_id, name, course_id) VALUES (60, 'Quality Assurance Seminar', 10);
INSERT INTO course_class (class_id, name, course_id) VALUES (61, 'Quality Assurance Lab', 10);
INSERT INTO course_class (class_id, name, course_id) VALUES (62, 'Special Topics in Quality Assurance', 10);
INSERT INTO course_class (class_id, name, course_id) VALUES (63, 'Quality Assurance Case Studies', 10);
INSERT INTO course_class (class_id, name, course_id) VALUES (64, 'Quality Assurance Lab', 10);
INSERT INTO course_class (class_id, name, course_id) VALUES (65, 'Quality Assurance Lab', 10);
INSERT INTO course_class (class_id, name, course_id) VALUES (66, 'Applied Quality Assurance', 10);
INSERT INTO course_class (class_id, name, course_id) VALUES (67, 'Data Science Fundamentals Workshop', 11);
INSERT INTO course_class (class_id, name, course_id) VALUES (68, 'Special Topics in Data Science Fundamentals', 11);
INSERT INTO course_class (class_id, name, course_id) VALUES (69, 'Data Science Fundamentals Seminar', 11);
INSERT INTO course_class (class_id, name, course_id) VALUES (70, 'Data Science Fundamentals Project', 11);
INSERT INTO course_class (class_id, name, course_id) VALUES (71, 'Data Science Fundamentals Lab', 11);
INSERT INTO course_class (class_id, name, course_id) VALUES (72, 'Introduction to Database Management', 12);
INSERT INTO course_class (class_id, name, course_id) VALUES (73, 'Database Management Case Studies', 12);
INSERT INTO course_class (class_id, name, course_id) VALUES (74, 'Applied Database Management', 12);
INSERT INTO course_class (class_id, name, course_id) VALUES (75, 'Special Topics in Blockchain Development', 13);
INSERT INTO course_class (class_id, name, course_id) VALUES (76, 'Introduction to Blockchain Development', 13);
INSERT INTO course_class (class_id, name, course_id) VALUES (77, 'Practical Blockchain Development', 13);
INSERT INTO course_class (class_id, name, course_id) VALUES (78, 'Introduction to Blockchain Development', 13);
INSERT INTO course_class (class_id, name, course_id) VALUES (79, 'Applied Blockchain Development', 13);
INSERT INTO course_class (class_id, name, course_id) VALUES (80, 'Blockchain Development Workshop', 13);
INSERT INTO course_class (class_id, name, course_id) VALUES (81, 'Special Topics in Blockchain Development', 13);
INSERT INTO course_class (class_id, name, course_id) VALUES (82, 'Blockchain Development Seminar', 13);
INSERT INTO course_class (class_id, name, course_id) VALUES (83, 'Special Topics in Internet of Things', 14);
INSERT INTO course_class (class_id, name, course_id) VALUES (84, 'Internet of Things Case Studies', 14);
INSERT INTO course_class (class_id, name, course_id) VALUES (85, 'Practical Internet of Things', 14);
INSERT INTO course_class (class_id, name, course_id) VALUES (86, 'Applied Internet of Things', 14);
INSERT INTO course_class (class_id, name, course_id) VALUES (87, 'Practical Internet of Things', 14);
INSERT INTO course_class (class_id, name, course_id) VALUES (88, 'Advanced Internet of Things', 14);
INSERT INTO course_class (class_id, name, course_id) VALUES (89, 'Internet of Things Case Studies', 14);
INSERT INTO course_class (class_id, name, course_id) VALUES (90, 'Applied Quality Assurance', 15);
INSERT INTO course_class (class_id, name, course_id) VALUES (91, 'Quality Assurance Lab', 15);
INSERT INTO course_class (class_id, name, course_id) VALUES (92, 'Quality Assurance Lab', 15);
INSERT INTO course_class (class_id, name, course_id) VALUES (93, 'Quality Assurance Lab', 15);
INSERT INTO course_class (class_id, name, course_id) VALUES (94, 'Advanced Quality Assurance', 15);
INSERT INTO course_class (class_id, name, course_id) VALUES (95, 'Quality Assurance Seminar', 15);
INSERT INTO course_class (class_id, name, course_id) VALUES (96, 'Quality Assurance Lab', 15);
INSERT INTO course_class (class_id, name, course_id) VALUES (97, 'Applied Quality Assurance', 15);
INSERT INTO course_class (class_id, name, course_id) VALUES (98, 'Practical Blockchain Development', 16);
INSERT INTO course_class (class_id, name, course_id) VALUES (99, 'Blockchain Development Workshop', 16);
INSERT INTO course_class (class_id, name, course_id) VALUES (100, 'Blockchain Development Project', 16);
INSERT INTO course_class (class_id, name, course_id) VALUES (101, 'Blockchain Development Case Studies', 16);
INSERT INTO course_class (class_id, name, course_id) VALUES (102, 'Advanced Blockchain Development', 16);
INSERT INTO course_class (class_id, name, course_id) VALUES (103, 'Blockchain Development Workshop', 16);
INSERT INTO course_class (class_id, name, course_id) VALUES (104, 'Blockchain Development Workshop', 16);
INSERT INTO course_class (class_id, name, course_id) VALUES (105, 'Applied Blockchain Development', 16);
INSERT INTO course_class (class_id, name, course_id) VALUES (106, 'Introduction to Quality Assurance', 17);
INSERT INTO course_class (class_id, name, course_id) VALUES (107, 'Applied Quality Assurance', 17);
INSERT INTO course_class (class_id, name, course_id) VALUES (108, 'Applied Quality Assurance', 17);
INSERT INTO course_class (class_id, name, course_id) VALUES (109, 'Quality Assurance Seminar', 17);
INSERT INTO course_class (class_id, name, course_id) VALUES (110, 'Quality Assurance Lab', 17);
INSERT INTO course_class (class_id, name, course_id) VALUES (111, 'Database Management Project', 18);
INSERT INTO course_class (class_id, name, course_id) VALUES (112, 'Special Topics in Database Management', 18);
INSERT INTO course_class (class_id, name, course_id) VALUES (113, 'Database Management Seminar', 18);
INSERT INTO course_class (class_id, name, course_id) VALUES (114, 'Database Management Lab', 18);
INSERT INTO course_class (class_id, name, course_id) VALUES (115, 'Database Management Seminar', 18);
INSERT INTO course_class (class_id, name, course_id) VALUES (116, 'Practical Internet of Things', 19);
INSERT INTO course_class (class_id, name, course_id) VALUES (117, 'Internet of Things Case Studies', 19);
INSERT INTO course_class (class_id, name, course_id) VALUES (118, 'Advanced Internet of Things', 19);
INSERT INTO course_class (class_id, name, course_id) VALUES (119, 'Internet of Things Seminar', 19);
INSERT INTO course_class (class_id, name, course_id) VALUES (120, 'Internet of Things Project', 19);
INSERT INTO course_class (class_id, name, course_id) VALUES (121, 'Internet of Things Seminar', 19);
INSERT INTO course_class (class_id, name, course_id) VALUES (122, 'Internet of Things Seminar', 19);
INSERT INTO course_class (class_id, name, course_id) VALUES (123, 'Internet of Things Case Studies', 19);
INSERT INTO course_class (class_id, name, course_id) VALUES (124, 'Introduction to Internet of Things', 20);
INSERT INTO course_class (class_id, name, course_id) VALUES (125, 'Special Topics in Internet of Things', 20);
INSERT INTO course_class (class_id, name, course_id) VALUES (126, 'Introduction to Internet of Things', 20);
INSERT INTO course_class (class_id, name, course_id) VALUES (127, 'Internet of Things Case Studies', 20);
INSERT INTO course_class (class_id, name, course_id) VALUES (128, 'Internet of Things Lab', 20);
INSERT INTO course_class (class_id, name, course_id) VALUES (129, 'Applied Internet of Things', 20);
INSERT INTO course_class (class_id, name, course_id) VALUES (130, 'Internet of Things Case Studies', 20);
INSERT INTO course_class (class_id, name, course_id) VALUES (131, 'Special Topics in Software Architecture', 21);
INSERT INTO course_class (class_id, name, course_id) VALUES (132, 'Practical Software Architecture', 21);
INSERT INTO course_class (class_id, name, course_id) VALUES (133, 'Special Topics in Software Architecture', 21);
INSERT INTO course_class (class_id, name, course_id) VALUES (134, 'Software Architecture Workshop', 21);
INSERT INTO course_class (class_id, name, course_id) VALUES (135, 'Applied Software Architecture', 21);
INSERT INTO course_class (class_id, name, course_id) VALUES (136, 'Practical Software Architecture', 21);
INSERT INTO course_class (class_id, name, course_id) VALUES (137, 'Practical Software Architecture', 21);
INSERT INTO course_class (class_id, name, course_id) VALUES (138, 'Cloud Computing Project', 22);
INSERT INTO course_class (class_id, name, course_id) VALUES (139, 'Advanced Cloud Computing', 22);
INSERT INTO course_class (class_id, name, course_id) VALUES (140, 'Cloud Computing Workshop', 22);
INSERT INTO course_class (class_id, name, course_id) VALUES (141, 'Cloud Computing Case Studies', 22);
INSERT INTO course_class (class_id, name, course_id) VALUES (142, 'Cloud Computing Case Studies', 22);
INSERT INTO course_class (class_id, name, course_id) VALUES (143, 'Introduction to Cloud Computing', 22);
INSERT INTO course_class (class_id, name, course_id) VALUES (144, 'Applied Machine Learning Basics', 23);
INSERT INTO course_class (class_id, name, course_id) VALUES (145, 'Machine Learning Basics Project', 23);
INSERT INTO course_class (class_id, name, course_id) VALUES (146, 'Machine Learning Basics Lab', 23);
INSERT INTO course_class (class_id, name, course_id) VALUES (147, 'Machine Learning Basics Seminar', 23);
INSERT INTO course_class (class_id, name, course_id) VALUES (148, 'Practical Machine Learning Basics', 23);
INSERT INTO course_class (class_id, name, course_id) VALUES (149, 'Advanced Machine Learning Basics', 23);
INSERT INTO course_class (class_id, name, course_id) VALUES (150, 'Special Topics in Machine Learning Basics', 23);
INSERT INTO course_class (class_id, name, course_id) VALUES (151, 'Machine Learning Basics Project', 23);
INSERT INTO course_class (class_id, name, course_id) VALUES (152, 'Practical Machine Learning Basics', 24);
INSERT INTO course_class (class_id, name, course_id) VALUES (153, 'Machine Learning Basics Lab', 24);
INSERT INTO course_class (class_id, name, course_id) VALUES (154, 'Machine Learning Basics Case Studies', 24);
INSERT INTO course_class (class_id, name, course_id) VALUES (155, 'Mobile App Development Project', 25);
INSERT INTO course_class (class_id, name, course_id) VALUES (156, 'Introduction to Mobile App Development', 25);
INSERT INTO course_class (class_id, name, course_id) VALUES (157, 'Mobile App Development Project', 25);
INSERT INTO course_class (class_id, name, course_id) VALUES (158, 'Mobile App Development Workshop', 25);
INSERT INTO course_class (class_id, name, course_id) VALUES (159, 'Advanced Mobile App Development', 25);
INSERT INTO course_class (class_id, name, course_id) VALUES (160, 'Mobile App Development Seminar', 25);
INSERT INTO course_class (class_id, name, course_id) VALUES (161, 'Introduction to Mobile App Development', 25);
INSERT INTO course_class (class_id, name, course_id) VALUES (162, 'Mobile App Development Workshop', 26);
INSERT INTO course_class (class_id, name, course_id) VALUES (163, 'Introduction to Mobile App Development', 26);
INSERT INTO course_class (class_id, name, course_id) VALUES (164, 'Mobile App Development Seminar', 26);
INSERT INTO course_class (class_id, name, course_id) VALUES (165, 'Mobile App Development Workshop', 26);
INSERT INTO course_class (class_id, name, course_id) VALUES (166, 'Introduction to Mobile App Development', 26);
INSERT INTO course_class (class_id, name, course_id) VALUES (167, 'Project Management Case Studies', 27);
INSERT INTO course_class (class_id, name, course_id) VALUES (168, 'Project Management Project', 27);
INSERT INTO course_class (class_id, name, course_id) VALUES (169, 'Special Topics in Project Management', 27);
INSERT INTO course_class (class_id, name, course_id) VALUES (170, 'Special Topics in Project Management', 27);
INSERT INTO course_class (class_id, name, course_id) VALUES (171, 'Project Management Seminar', 27);
INSERT INTO course_class (class_id, name, course_id) VALUES (172, 'Project Management Case Studies', 27);
INSERT INTO course_class (class_id, name, course_id) VALUES (173, 'Cloud Computing Lab', 28);
INSERT INTO course_class (class_id, name, course_id) VALUES (174, 'Special Topics in Cloud Computing', 28);
INSERT INTO course_class (class_id, name, course_id) VALUES (175, 'Practical Cloud Computing', 28);
INSERT INTO course_class (class_id, name, course_id) VALUES (176, 'Applied Cloud Computing', 28);
INSERT INTO course_class (class_id, name, course_id) VALUES (177, 'Special Topics in Machine Learning Basics', 29);
INSERT INTO course_class (class_id, name, course_id) VALUES (178, 'Practical Machine Learning Basics', 29);
INSERT INTO course_class (class_id, name, course_id) VALUES (179, 'Special Topics in Machine Learning Basics', 29);
INSERT INTO course_class (class_id, name, course_id) VALUES (180, 'Introduction to Machine Learning Basics', 29);
INSERT INTO course_class (class_id, name, course_id) VALUES (181, 'Applied Machine Learning Basics', 29);
INSERT INTO course_class (class_id, name, course_id) VALUES (182, 'Advanced Internet of Things', 30);
INSERT INTO course_class (class_id, name, course_id) VALUES (183, 'Internet of Things Seminar', 30);
INSERT INTO course_class (class_id, name, course_id) VALUES (184, 'Practical Internet of Things', 30);
INSERT INTO course_class (class_id, name, course_id) VALUES (185, 'Internet of Things Case Studies', 30);
INSERT INTO course_class (class_id, name, course_id) VALUES (186, 'Applied Quality Assurance', 31);
INSERT INTO course_class (class_id, name, course_id) VALUES (187, 'Quality Assurance Lab', 31);
INSERT INTO course_class (class_id, name, course_id) VALUES (188, 'Introduction to Quality Assurance', 31);
INSERT INTO course_class (class_id, name, course_id) VALUES (189, 'Quality Assurance Seminar', 31);
INSERT INTO course_class (class_id, name, course_id) VALUES (190, 'Quality Assurance Seminar', 31);
INSERT INTO course_class (class_id, name, course_id) VALUES (191, 'Quality Assurance Case Studies', 31);
INSERT INTO course_class (class_id, name, course_id) VALUES (192, 'Quality Assurance Seminar', 31);
INSERT INTO course_class (class_id, name, course_id) VALUES (193, 'DevOps Practices Workshop', 32);
INSERT INTO course_class (class_id, name, course_id) VALUES (194, 'DevOps Practices Lab', 32);
INSERT INTO course_class (class_id, name, course_id) VALUES (195, 'Practical DevOps Practices', 32);
INSERT INTO course_class (class_id, name, course_id) VALUES (196, 'Introduction to Artificial Intelligence', 33);
INSERT INTO course_class (class_id, name, course_id) VALUES (197, 'Applied Artificial Intelligence', 33);
INSERT INTO course_class (class_id, name, course_id) VALUES (198, 'Artificial Intelligence Seminar', 33);
INSERT INTO course_class (class_id, name, course_id) VALUES (199, 'Special Topics in Artificial Intelligence', 33);
INSERT INTO course_class (class_id, name, course_id) VALUES (200, 'Artificial Intelligence Project', 33);
INSERT INTO course_class (class_id, name, course_id) VALUES (201, 'Introduction to Internet of Things', 34);
INSERT INTO course_class (class_id, name, course_id) VALUES (202, 'Special Topics in Internet of Things', 34);
INSERT INTO course_class (class_id, name, course_id) VALUES (203, 'Internet of Things Project', 34);
INSERT INTO course_class (class_id, name, course_id) VALUES (204, 'Internet of Things Seminar', 34);
INSERT INTO course_class (class_id, name, course_id) VALUES (205, 'Internet of Things Workshop', 34);
INSERT INTO course_class (class_id, name, course_id) VALUES (206, 'Introduction to Internet of Things', 34);
INSERT INTO course_class (class_id, name, course_id) VALUES (207, 'Internet of Things Project', 35);
INSERT INTO course_class (class_id, name, course_id) VALUES (208, 'Internet of Things Workshop', 35);
INSERT INTO course_class (class_id, name, course_id) VALUES (209, 'Introduction to Internet of Things', 35);
INSERT INTO course_class (class_id, name, course_id) VALUES (210, 'Internet of Things Lab', 35);
INSERT INTO course_class (class_id, name, course_id) VALUES (211, 'Practical Internet of Things', 35);
INSERT INTO course_class (class_id, name, course_id) VALUES (212, 'Advanced Internet of Things', 35);
INSERT INTO course_class (class_id, name, course_id) VALUES (213, 'Internet of Things Seminar', 35);
INSERT INTO course_class (class_id, name, course_id) VALUES (214, 'Internet of Things Project', 35);
INSERT INTO course_class (class_id, name, course_id) VALUES (215, 'Data Analytics Case Studies', 36);
INSERT INTO course_class (class_id, name, course_id) VALUES (216, 'Data Analytics Seminar', 36);
INSERT INTO course_class (class_id, name, course_id) VALUES (217, 'Advanced Data Analytics', 36);
INSERT INTO course_class (class_id, name, course_id) VALUES (218, 'Data Analytics Project', 36);
INSERT INTO course_class (class_id, name, course_id) VALUES (219, 'Data Analytics Project', 36);
INSERT INTO course_class (class_id, name, course_id) VALUES (220, 'Advanced Data Analytics', 36);
INSERT INTO course_class (class_id, name, course_id) VALUES (221, 'Data Analytics Case Studies', 36);
INSERT INTO course_class (class_id, name, course_id) VALUES (222, 'Data Analytics Case Studies', 36);
INSERT INTO course_class (class_id, name, course_id) VALUES (223, 'Data Science Fundamentals Lab', 37);
INSERT INTO course_class (class_id, name, course_id) VALUES (224, 'Practical Data Science Fundamentals', 37);
INSERT INTO course_class (class_id, name, course_id) VALUES (225, 'Practical Data Science Fundamentals', 37);
INSERT INTO course_class (class_id, name, course_id) VALUES (226, 'Data Science Fundamentals Project', 37);
INSERT INTO course_class (class_id, name, course_id) VALUES (227, 'Internet of Things Project', 38);
INSERT INTO course_class (class_id, name, course_id) VALUES (228, 'Internet of Things Project', 38);
INSERT INTO course_class (class_id, name, course_id) VALUES (229, 'Special Topics in Internet of Things', 38);
INSERT INTO course_class (class_id, name, course_id) VALUES (230, 'Cloud Computing Workshop', 39);
INSERT INTO course_class (class_id, name, course_id) VALUES (231, 'Cloud Computing Project', 39);
INSERT INTO course_class (class_id, name, course_id) VALUES (232, 'Advanced Cloud Computing', 39);
INSERT INTO course_class (class_id, name, course_id) VALUES (233, 'Cloud Computing Project', 39);
INSERT INTO course_class (class_id, name, course_id) VALUES (234, 'Cloud Computing Seminar', 39);
INSERT INTO course_class (class_id, name, course_id) VALUES (235, 'Project Management Seminar', 40);
INSERT INTO course_class (class_id, name, course_id) VALUES (236, 'Applied Project Management', 40);
INSERT INTO course_class (class_id, name, course_id) VALUES (237, 'Special Topics in Project Management', 40);
INSERT INTO course_class (class_id, name, course_id) VALUES (238, 'Project Management Project', 40);
INSERT INTO course_class (class_id, name, course_id) VALUES (239, 'Project Management Seminar', 40);
INSERT INTO course_class (class_id, name, course_id) VALUES (240, 'Applied Project Management', 40);
INSERT INTO course_class (class_id, name, course_id) VALUES (241, 'Project Management Case Studies', 40);
INSERT INTO course_class (class_id, name, course_id) VALUES (242, 'Practical Artificial Intelligence', 41);
INSERT INTO course_class (class_id, name, course_id) VALUES (243, 'Artificial Intelligence Project', 41);
INSERT INTO course_class (class_id, name, course_id) VALUES (244, 'Artificial Intelligence Lab', 41);
INSERT INTO course_class (class_id, name, course_id) VALUES (245, 'Advanced Artificial Intelligence', 41);
INSERT INTO course_class (class_id, name, course_id) VALUES (246, 'Introduction to Artificial Intelligence', 41);
INSERT INTO course_class (class_id, name, course_id) VALUES (247, 'Artificial Intelligence Seminar', 41);
INSERT INTO course_class (class_id, name, course_id) VALUES (248, 'Artificial Intelligence Seminar', 42);
INSERT INTO course_class (class_id, name, course_id) VALUES (249, 'Artificial Intelligence Workshop', 42);
INSERT INTO course_class (class_id, name, course_id) VALUES (250, 'Artificial Intelligence Lab', 42);
INSERT INTO course_class (class_id, name, course_id) VALUES (251, 'Artificial Intelligence Seminar', 42);
INSERT INTO course_class (class_id, name, course_id) VALUES (252, 'Special Topics in DevOps Practices', 43);
INSERT INTO course_class (class_id, name, course_id) VALUES (253, 'DevOps Practices Seminar', 43);
INSERT INTO course_class (class_id, name, course_id) VALUES (254, 'DevOps Practices Lab', 43);
INSERT INTO course_class (class_id, name, course_id) VALUES (255, 'Advanced DevOps Practices', 43);
INSERT INTO course_class (class_id, name, course_id) VALUES (256, 'DevOps Practices Case Studies', 43);
INSERT INTO course_class (class_id, name, course_id) VALUES (257, 'Advanced DevOps Practices', 43);
INSERT INTO course_class (class_id, name, course_id) VALUES (258, 'DevOps Practices Lab', 43);
INSERT INTO course_class (class_id, name, course_id) VALUES (259, 'Data Analytics Project', 44);
INSERT INTO course_class (class_id, name, course_id) VALUES (260, 'Introduction to Data Analytics', 44);
INSERT INTO course_class (class_id, name, course_id) VALUES (261, 'Data Analytics Workshop', 44);
INSERT INTO course_class (class_id, name, course_id) VALUES (262, 'Data Analytics Workshop', 44);
INSERT INTO course_class (class_id, name, course_id) VALUES (263, 'Practical Data Analytics', 44);
INSERT INTO course_class (class_id, name, course_id) VALUES (264, 'Agile Methodologies Case Studies', 45);
INSERT INTO course_class (class_id, name, course_id) VALUES (265, 'Agile Methodologies Case Studies', 45);
INSERT INTO course_class (class_id, name, course_id) VALUES (266, 'Agile Methodologies Workshop', 45);
INSERT INTO course_class (class_id, name, course_id) VALUES (267, 'Advanced Agile Methodologies', 45);
INSERT INTO course_class (class_id, name, course_id) VALUES (268, 'Data Science Fundamentals Workshop', 46);
INSERT INTO course_class (class_id, name, course_id) VALUES (269, 'Practical Data Science Fundamentals', 46);
INSERT INTO course_class (class_id, name, course_id) VALUES (270, 'Introduction to Data Science Fundamentals', 46);
INSERT INTO course_class (class_id, name, course_id) VALUES (271, 'Special Topics in Data Science Fundamentals', 46);
INSERT INTO course_class (class_id, name, course_id) VALUES (272, 'Data Science Fundamentals Workshop', 46);
INSERT INTO course_class (class_id, name, course_id) VALUES (273, 'Applied Data Science Fundamentals', 46);
INSERT INTO course_class (class_id, name, course_id) VALUES (274, 'Advanced Project Management', 47);
INSERT INTO course_class (class_id, name, course_id) VALUES (275, 'Special Topics in Project Management', 47);
INSERT INTO course_class (class_id, name, course_id) VALUES (276, 'Project Management Workshop', 47);
INSERT INTO course_class (class_id, name, course_id) VALUES (277, 'Project Management Lab', 47);
INSERT INTO course_class (class_id, name, course_id) VALUES (278, 'Advanced Blockchain Development', 48);
INSERT INTO course_class (class_id, name, course_id) VALUES (279, 'Practical Blockchain Development', 48);
INSERT INTO course_class (class_id, name, course_id) VALUES (280, 'Special Topics in Blockchain Development', 48);
INSERT INTO course_class (class_id, name, course_id) VALUES (281, 'Practical Blockchain Development', 48);
INSERT INTO course_class (class_id, name, course_id) VALUES (282, 'Applied Blockchain Development', 48);
INSERT INTO course_class (class_id, name, course_id) VALUES (283, 'Advanced Blockchain Development', 48);
INSERT INTO course_class (class_id, name, course_id) VALUES (284, 'Artificial Intelligence Seminar', 49);
INSERT INTO course_class (class_id, name, course_id) VALUES (285, 'Applied Artificial Intelligence', 49);
INSERT INTO course_class (class_id, name, course_id) VALUES (286, 'Applied Artificial Intelligence', 49);
INSERT INTO course_class (class_id, name, course_id) VALUES (287, 'Applied Artificial Intelligence', 49);
INSERT INTO course_class (class_id, name, course_id) VALUES (288, 'Database Management Seminar', 50);
INSERT INTO course_class (class_id, name, course_id) VALUES (289, 'Introduction to Database Management', 50);
INSERT INTO course_class (class_id, name, course_id) VALUES (290, 'Database Management Seminar', 50);
INSERT INTO course_class (class_id, name, course_id) VALUES (291, 'Advanced Database Management', 50);
INSERT INTO course_class (class_id, name, course_id) VALUES (292, 'Database Management Seminar', 50);
INSERT INTO course_class (class_id, name, course_id) VALUES (293, 'Practical Database Management', 50);
INSERT INTO course_class (class_id, name, course_id) VALUES (294, 'Database Management Seminar', 50);
INSERT INTO course_class (class_id, name, course_id) VALUES (295, 'Applied Database Management', 50);

COMMIT;

SET FOREIGN_KEY_CHECKS=1;
