-- Generated on 2025-01-09 00:35:37
-- COMMIT EVERY 1000 ROWS

SET FOREIGN_KEY_CHECKS=0;

INSERT INTO course ( name, maxpeople, price) VALUES ( 'Software Architecture', 38, 2559.9);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'UI/UX Design', 35, 1843.64);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'DevOps Practices', 88, 1576.66);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Business Analytics', 87, 2729.05);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Mobile App Development', 28, 526.7);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Database Management', 40, 2970.32);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Java Development', 94, 575.95);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Software Architecture', 20, 2534.89);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Project Management', 46, 1336.75);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Database Management', 91, 2820.51);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Data Science Fundamentals', 64, 1551.48);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Internet of Things', 49, 1848.78);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Mobile App Development', 51, 1930.42);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Blockchain Development', 66, 1158.19);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Machine Learning Basics', 23, 1260.2);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Mobile App Development', 28, 1915.37);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Network Security', 53, 1188.83);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Machine Learning Basics', 79, 534.82);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Mobile App Development', 61, 859.71);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Data Analytics', 82, 2815.79);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Quality Assurance', 58, 790.99);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Python Programming', 28, 2462.96);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Software Architecture', 42, 2971.73);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Quality Assurance', 92, 1834.29);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Web Technologies', 48, 2418.33);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Database Management', 32, 1492.9);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Database Management', 71, 2220.75);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Mobile App Development', 94, 1284.74);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Business Analytics', 61, 2447.81);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Cloud Computing', 61, 1854.93);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Cloud Computing', 30, 2395.68);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Business Analytics', 49, 2489.44);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Java Development', 58, 1018.58);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Machine Learning Basics', 25, 1868.7);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Software Architecture', 81, 770.98);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Python Programming', 51, 2785.61);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Web Technologies', 29, 1401.86);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Network Security', 98, 2943.17);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Python Programming', 60, 2423.39);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Database Management', 34, 2621.8);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Machine Learning Basics', 75, 1205.25);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Business Analytics', 63, 1279.96);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Internet of Things', 66, 718.9);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Mobile App Development', 41, 2915.41);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Project Management', 50, 2835.35);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Internet of Things', 82, 2272.15);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Network Security', 26, 2843.62);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Data Science Fundamentals', 54, 2054.2);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Mobile App Development', 48, 2852.3);
INSERT INTO course ( name, maxpeople, price) VALUES ( 'Quality Assurance', 60, 809.01);
